/* Explainable local growth scenarios. No external AI or provider calls. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.EmberEdge=factory()})(typeof globalThis!=='undefined'?globalThis:this,function(){
const DAY=86400000,copy=x=>JSON.parse(JSON.stringify(x)),check=(v,m)=>{if(!v)throw Error(m)},num=(v,min=0,max=1e8)=>{v=Number(v);check(Number.isFinite(v)&&v>=min&&v<=max,'Value outside allowed range');return v},round=x=>Math.round(x*100)/100;
function attach(E){
function init(){if(!E.db.edge)E.db.edge={version:1,policy:{limit:300,minMargin:25},cases:[{id:'rc1',customer:'c4',issue:'Missing item',detail:'Sandwich was missing from the pickup order.',severity:'Medium',status:'Open',created:E.db.now-2*DAY,offer:'o1',reply:'',cost:72},{id:'rc2',customer:'c9',issue:'Late order',detail:'Order arrived 35 minutes later than promised.',severity:'High',status:'Open',created:E.db.now-DAY,offer:'o2',reply:'',cost:150},{id:'rc3',customer:'c2',issue:'Wrong item',detail:'Guest received a different drink.',severity:'Low',status:'Open',created:E.db.now,offer:'o1',reply:'',cost:72}],experiences:[{id:'xp1',name:'After-hours coffee tasting',kind:'Experience',description:'A guided tasting for two with the head barista.',points:1200,cost:180,stock:12,tier:'Any',store:'all',active:true},{id:'xp2',name:'The secret seasonal menu',kind:'Exclusive access',description:'Unlock a members-only seasonal selection.',points:300,cost:25,stock:50,tier:'Any',store:'all',active:true},{id:'xp3',name:'Priority pickup for a month',kind:'VIP perk',description:'A dedicated pickup benefit for your next visits.',points:800,cost:50,stock:30,tier:'Gold',store:'all',active:true},{id:'xp4',name:'Partner pottery workshop',kind:'Partner benefit',description:'A reserved community workshop seat.',points:1800,cost:250,stock:8,tier:'Any',store:'s0',active:true}],bookings:[],experiments:[{id:'exp1',name:'Welcome perk vs ₹150 incentive',segment:'all',status:'Draft',budget:4000,orderValue:650,margin:60,controlRate:12,perkRate:18,discountRate:20,perkCost:40,discountCost:150,observations:[],created:E.db.now}],briefs:[]};return E.db.edge}
const db=()=>init(),member=id=>{const c=E.find('customers',id);E.permission('customers',c.store);return c};
function insight(c){const tx=E.db.transactions.filter(t=>t.customer===c.id&&t.status==='Completed').sort((a,b)=>b.date-a.date),days=E.customerDays(c),avg=tx.length?tx.reduce((s,t)=>s+t.net,0)/tx.length:0;const gaps=tx.slice(1).map((t,i)=>(tx[i].date-t.date)/DAY),cadence=gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:30;const overdue=Math.max(0,days-cadence),risk=Math.min(95,Math.max(5,Math.round(15+overdue*1.5+(db().cases.some(r=>r.customer===c.id&&r.status!=='Resolved')?20:0))));return {days,avg:round(avg),cadence:Math.round(cadence),risk,clv:round(avg*365/Math.max(7,cadence)*(1-risk/100)),next:Math.max(0,Math.round(cadence-days)),reason:`${days} days since last visit; typical interval ${Math.round(cadence)} days.`,action:db().cases.some(r=>r.customer===c.id&&r.status!=='Resolved')?'Resolve the open service issue':risk>=60?'Try a targeted win-back perk':c.visits<3?'Encourage the next visit':'Offer an exclusive experience',favorite:c.tags?.[0]||'Not yet known'}}
function brief(input){const goal=input.goal.toLowerCase();let segment=/risk|back|lapsed|return/.test(goal)?'seg1':/gold|vip|valuable/.test(goal)?'seg2':'all';const list=E.segment(segment);return {name:input.name||'Copilot · '+input.goal.slice(0,55),goal:input.goal,segment,channel:input.channel||'Email',offer:input.offer||'o1',message:'Hi {{first_name}}, we have something special waiting for your next visit. Explore your member reward.',budget:num(input.budget||3000),reason:segment==='seg1'?'Uses the existing at-risk audience: inactive regulars.':segment==='seg2'?'Uses the existing Gold audience.':'Uses all accessible members; refine the audience before saving.',count:list.length}}
function plan(input){const reachable=E.campaignReach({segment:input.segment,channel:input.channel,store:input.store||''});const n=reachable.length,cost=num(input.cost),rate=num(input.rate,0,100)/100,order=num(input.orderValue),margin=num(input.margin,0,100)/100;return {n,redemptions:n*rate,cost:round(n*rate*cost),contribution:round(n*rate*(order*margin-cost)),eligible:reachable.map(c=>c.id)}}
function results(x){const out=['Control','Perk','Discount'].map(group=>{const rows=x.observations.filter(r=>r.group===group),buyers=rows.filter(r=>r.purchased);return {group,n:rows.length,buyers:buyers.length,rate:rows.length?buyers.length/rows.length:0,revenue:round(buyers.reduce((s,r)=>s+r.revenue,0)),cost:round(buyers.reduce((s,r)=>s+r.cost,0))}});const control=out[0];return out.map(r=>({...r,lift:round((r.rate-control.rate)*100),incremental:round((r.revenue-r.n*(control.n?control.revenue/control.n:0))*x.margin/100-r.cost)}))}
return {init,insight,brief,plan,results,get data(){return db()},
saveBrief(input){return E.atomic('campaigns','Saved copilot brief',()=>{const b={...copy(input),id:E.id('brief'),created:E.db.now};db().briefs.unshift(b);return b})},
createCampaign(input){check(input.message.trim(),'Add a message');const p=plan(input);check(p.n>0,'No consented members in this audience');check(p.cost<=num(input.budget),'Expected reward cost exceeds budget');const c=E.saveCampaign({...input,ab:false,messageB:'',control:10,repeat:0,tags:['Copilot'],submit:true});E.atomic('campaigns','Recorded campaign forecast',()=>{db().briefs.unshift({...copy(input),id:E.id('brief'),campaign:c.id,forecast:p,created:E.db.now});return c});return c},
newCase(input){return E.atomic('customers','Opened recovery case',()=>{member(input.customer);check(input.detail.trim(),'Describe the issue');const r={...input,id:E.id('rc'),status:'Open',created:E.db.now,cost:72,offer:'o1',reply:''};db().cases.unshift(r);return r})},
propose(id,input){return E.atomic('customers','Proposed recovery',()=>{const r=db().cases.find(x=>x.id===id);check(r,'Case not found');member(r.customer);check(['Open','Escalated'].includes(r.status),'Case already has a resolution');const cost=num(input.cost),limit=db().policy.limit;E.find('offers',input.offer);check(input.reply.trim(),'Write a reply');Object.assign(r,input,{cost,status:cost>limit||r.severity==='High'?'Escalated':'Pending approval'});return r})},
resolve(id){return E.atomic('offers','Approved recovery and issued reward',()=>{check(E.role().id==='owner','Owner approval is required');const r=db().cases.find(x=>x.id===id);check(r&&['Pending approval','Escalated'].includes(r.status),'Propose a resolution first');const c=member(r.customer);check(c.status==='Active','Member is frozen');const o=E.find('offers',r.offer);check(o.active&&o.expiry>=E.db.now,'Choose an active, unexpired offer');c.issued.unshift({id:E.id('gift'),offer:o.id,date:E.db.now,reason:'Recovery '+r.id,used:false});r.status='Resolved';r.resolved=E.db.now;r.baseline=E.db.transactions.filter(t=>t.customer===c.id).map(t=>t.id);E.emit('Recovery resolved',c.id,{case:r.id,message:r.reply});return r})},
returned(r){return r.status==='Resolved'?E.db.transactions.filter(t=>t.customer===r.customer&&t.status==='Completed'&&!r.baseline.includes(t.id)&&t.date>=r.resolved):[]},
policy(input){return E.atomic('settings','Updated recovery guardrails',()=>{db().policy.limit=num(input.limit);return 'Policy saved'})},
saveExperience(input){return E.atomic('offers','Saved experience',()=>{check(input.name.trim(),'Add a name');const x={...input,points:num(input.points),cost:num(input.cost),stock:num(input.stock),active:true};check(Number.isInteger(x.points)&&Number.isInteger(x.stock),'Points and capacity must be whole numbers');if(x.id){Object.assign(db().experiences.find(y=>y.id===x.id),x)}else{x.id=E.id('xp');db().experiences.unshift(x)}return x})},
book(id,customer){return E.atomic('engagement','Reserved member experience',()=>{const x=db().experiences.find(x=>x.id===id),c=member(customer);check(x&&x.active&&x.stock>0,'Experience unavailable');check(c.status==='Active','Member is frozen');check(x.tier==='Any'||x.tier===c.tier,'Member does not meet tier requirement');check(x.store==='all'||x.store===c.store,'Experience restricted to its location');check(!db().bookings.some(b=>b.customer===customer&&b.experience===id&&b.status==='Reserved'),'Member already has a reservation');E.point(c,-x.points,x.name,'Experience');x.stock--;const b={id:E.id('booking'),experience:id,customer,points:x.points,status:'Reserved',created:E.db.now};db().bookings.unshift(b);E.emit('Experience reserved',customer,{booking:b.id});return b})},
booking(id,action){return E.atomic('engagement',action+' experience reservation',()=>{const b=db().bookings.find(x=>x.id===id);check(b&&b.status==='Reserved','Only a reserved experience can be changed');const c=member(b.customer);check(['Fulfill','Cancel'].includes(action),'Invalid action');if(action==='Cancel'){E.point(c,b.points,'Cancelled experience','Refund');db().experiences.find(x=>x.id===b.experience).stock++}b.status=action==='Cancel'?'Cancelled':'Fulfilled';return b})},
saveExperiment(input){return E.atomic('campaigns','Created experiment',()=>{check(input.name.trim(),'Name required');const x={...copy(input),id:E.id('exp'),status:'Draft',observations:[],created:E.db.now};['budget','orderValue','perkCost','discountCost'].forEach(k=>x[k]=num(x[k]));['margin','controlRate','perkRate','discountRate'].forEach(k=>x[k]=num(x[k],0,100));db().experiments.unshift(x);return x})},
run(id){return E.atomic('campaigns','Ran synthetic experiment',()=>{const x=db().experiments.find(x=>x.id===id);check(x&&x.status==='Draft','This experiment has already run');const audience=E.segment(x.segment).filter(c=>c.status==='Active');check(audience.length>=6,'Select at least six members');const groups=['Control','Perk','Discount'];x.observations=audience.map((c,i)=>({customer:c.id,group:groups[i%3],purchased:false,revenue:0,cost:0}));groups.forEach((group,i)=>{const rows=x.observations.filter(r=>r.group===group),rate=[x.controlRate,x.perkRate,x.discountRate][i],wins=Math.round(rows.length*rate/100);rows.forEach((r,j)=>{r.purchased=j<wins;r.revenue=r.purchased?x.orderValue:0;r.cost=r.purchased?[0,x.perkCost,x.discountCost][i]:0})});check(x.observations.reduce((s,r)=>s+r.cost,0)<=x.budget,'Scenario reward costs exceed budget; increase budget or reduce incentives');x.status='Simulated';return x})}
}}
return {attach};});
