/* Ember expanded workspace. All integrations and payments are local simulations. */
(function(){
'use strict';
let initial;try{initial=JSON.parse(localStorage.getItem('ember-v3')||'null')}catch{}
const E=EmberEngine.create({data:initial?.version===3?initial:undefined,legacy:!initial?{customers}:undefined,storage:localStorage});window.ember=E;
const U={store:'all',period:30,tab:{},search:'',tier:'all',selected:'c1',campaignStatus:'All',quote:null,basket:{customer:'c1',store:'s0',lines:[{product:'p1',qty:2},{product:'p3',qty:1}],offers:[],code:'',payment:'External demo',channel:'In store',reference:'DEMO-1001',campaign:''},filter:'',pending:null};
const db=()=>E.db, e=esc, number=n=>Number(n||0).toLocaleString('en-IN'), date=t=>new Date(t).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}), time=t=>new Date(t).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}), pct=n=>Number(n||0).toFixed(1)+'%', D=EmberEngine.DAY;
const B=(text,action,value='',primary=false)=>`<button type="button" ${primary?'class="primary"':''} data-do="${action}" data-id="${e(value)}">${text}</button>`;
const link=(text,route)=>`<a class="link-button" href="#${route}">${text}</a>`;
const tag=(s)=>`<span class="badge ${['Draft','Paused','Cancelled','Archived','Disabled'].includes(s)?'draft':['Pending approval','Scheduled','Queued','Pending','Failed','Open'].includes(s)?'scheduled':['Frozen','Confirmed','Disapproved'].includes(s)?'risk':s==='Gold'?'gold':''}">${e(s)}</span>`;
const input=(label,key,value='',type='text',attrs='')=>`<label class="field">${label}<input name="${key}" type="${type}" value="${e(value)}" ${attrs}></label>`;
const select=(label,key,options,value,attrs='')=>`<label class="field">${label}<select name="${key}" ${attrs}>${options.map(o=>{let a=Array.isArray(o)?o:[o,o];return `<option value="${e(a[0])}" ${String(value)===String(a[0])?'selected':''}>${e(a[1])}</option>`}).join('')}</select></label>`;
const check=(label,key,on)=>`<label class="check-field"><input type="checkbox" name="${key}" ${on?'checked':''}> ${label}</label>`;
const area=(label,key,value='',attrs='required')=>`<label class="field">${label}<textarea name="${key}" ${attrs}>${e(value)}</textarea></label>`;
const options=(arr)=>arr.map(x=>[x.id,x.name]);
const cOptions=()=>options(E.segment('all')),sOptions=()=>options(db().stores.filter(s=>!E.role().stores.length||E.role().stores.includes(s.id))),oOptions=()=>options(db().offers.filter(o=>o.active));
const form=(id,body,submit='Save changes',key='')=>`<form data-form="${id}" data-id="${e(key)}">${body}<div class="form-actions">${B('Cancel','close')}<button class="primary" type="submit">${submit}</button></div><p class="form-error" role="alert"></p></form>`;
const panel=(title,body,action='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div><div class="padded">${body}</div></section>`;
const notice=t=>`<div class="notice">${t}</div>`;
const empty=(title,body='Adjust your filters or create a record to get started.')=>`<div class="empty"><h3>${title}</h3><p>${body}</p></div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">${empty('No matching records')}</td></tr>`}</tbody></table></div>`;
const metrics=items=>`<div class="stats">${items.map(([label,value,sub])=>`<div class="stat"><div class="stat-top">${label}</div><div class="stat-value">${value}</div><div class="secondary">${sub||'From the current demo dataset'}</div></div>`).join('')}</div>`;
function page(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`}
const filterBar=()=>`<div class="toolbar"><div class="filters"><select id="x-store" aria-label="Store scope"><option value="all">All accessible stores</option>${sOptions().map(([id,n])=>`<option value="${id}" ${U.store===id?'selected':''}>${e(n)}</option>`).join('')}</select><select id="x-period" aria-label="Report period">${[7,30,90,180,365].map(n=>`<option value="${n}" ${U.period===n?'selected':''}>Last ${n} days</option>`).join('')}</select></div><span class="period">Demo clock · ${date(db().now)}</span></div>`;
function tabs(items){const route=state.route;const current=U.tab[route]||items[0][0];return `<div class="tab-row">${items.map(([id,t])=>`<button data-do="tab" data-id="${id}" class="${current===id?'selected':''}">${t}</button>`).join('')}</div>`}
const tabIs=(x,first)=> (U.tab[state.route]||first)===x;
const activity=()=>table(['WHEN','ACTION','ACTOR','DETAIL'],db().audit.slice(0,20).map(a=>[time(a.date),e(a.action),e(a.actor),e(a.detail)]));
function show(title,body,wide=false){modal(title,body);$('#modal').classList.toggle('wide-modal',wide)}
function done(message){$('#modal').close();render();toast(message)}
function download(name,data,type='text/plain'){const blob=new Blob([data],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(dataset,fields){const rows=dataset.map(r=>fields.map(k=>{let v=r[k];if(typeof v==='object')v=JSON.stringify(v);v=String(v??'');if(/^[=+\-@]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'}).join(','));return '\uFEFF'+fields.join(',')+'\n'+rows.join('\n')}
function reportExport(dataset,fields){assertExport();const rows=db()[dataset].filter(r=>!r.store||!E.role().stores.length||E.role().stores.includes(r.store));download('ember-'+dataset+'.csv',csv(rows,fields),'text/csv');toast('CSV exported')}
function assertExport(){if(!E.role().export)throw Error('This demo role cannot export data')}
const groups=[['Workspace',[['overview','Overview','overview'],['customers','Customers','customers'],['segments','Audiences','customers']]],['Loyalty & commerce',[['loyalty','Loyalty program','loyalty'],['rewards','Rewards & offers','rewards'],['checkout','Checkout simulator','stores'],['memberships','Memberships','loyalty'],['wallet','Member experience','customers']]],['Marketing',[['campaigns','Campaigns','campaigns'],['journeys','Journeys','journeys'],['engagement','Engagement studio','loyalty'],['merchandise','Merchandise','rewards']]],['Operations',[['stores','Stores','stores'],['analytics','Reports','analytics'],['fraud','Fraud review','settings'],['integrations','Integrations','integrations'],['data','Data center','analytics']]],['Control center',[['team','Team & permissions','customers'],['lab','Growth lab','analytics'],['coverage','Feature map','overview'],['settings','Settings & audit','settings']]]];
routes.splice(0,routes.length,...groups.flatMap(g=>g[1].map(r=>[r[0],r[1]])));
const scopes={customers:'customers',segments:'campaigns',loyalty:'loyalty',rewards:'offers',checkout:'checkout',memberships:'memberships',wallet:'wallet',campaigns:'campaigns',journeys:'campaigns',engagement:'engagement',merchandise:'engagement',stores:'settings',fraud:'fraud',integrations:'integrations',data:'data',team:'team',settings:'settings',lab:'campaigns'};
const accessible=route=>!scopes[route]||E.role().permissions.includes(scopes[route]);
window.afterRender=()=>{
 $('#nav').innerHTML=groups.map(([name,items],idx)=>`<details class="nav-group" ${items.some(r=>r[0]===state.route)||idx===0||window.innerWidth<=900?'open':''}><summary>${name}</summary>${items.filter(r=>accessible(r[0])).map(([key,label,ico])=>`<a href="#${key}" title="${label}" class="${state.route===key?'active':''}">${icon(ico)}<span>${label}</span>${key==='fraud'&&db().fraudCases.filter(f=>f.status==='Open').length?`<span class="nav-count">${db().fraudCases.filter(f=>f.status==='Open').length}</span>`:''}</a>`).join('')}</details>`).join('');
 $('.workspace strong').textContent=db().settings.workspace;$('.workspace small').textContent='Local simulation workspace';$('.health').innerHTML='<span class="live-dot"></span> Local demo · no live connections';
 $('.header-right').innerHTML=`${B('⌕ &nbsp; Search','command')}<select id="x-role" aria-label="Simulate role">${db().roles.map(r=>`<option value="${r.id}" ${E.role().id===r.id?'selected':''}>${e(r.name)} · demo</option>`).join('')}</select><button class="icon-button" data-do="notifications" aria-label="Notifications">${icon('campaigns')}</button>`;
 $('footer').innerHTML=`EMBER LOYALTY CLOUD <span>Local prototype · ${date(db().now)} · Changes saved on this device</span>`;
 if(!accessible(state.route))$('#main').innerHTML=page('This role has limited access.','Choose an allowed section or switch the demo role to Owner.')+notice('Role switching previews permissions. Production access control requires a server.');
 document.querySelectorAll('form button[data-do]').forEach(b=>b.type='button');
};
const originalRender=render;render=function(){originalRender();window.afterRender()};
window.addEventListener('resize',()=>window.afterRender());
window.addEventListener('hashchange',()=>{window.afterRender();window.scrollTo({top:0,behavior:'instant'})});
function revenueChart(){let points=Array.from({length:12},(_,i)=>{let start=db().now-U.period*D+i*U.period*D/12,end=start+U.period*D/12;return E.totals(U.store,U.period).rows.filter(t=>t.date>=start&&t.date<end).reduce((s,t)=>s+t.net,0)});const max=Math.max(...points,1),path=points.map((n,i)=>(i?'L':'M')+(45+i*48)+' '+(175-n/max*145)).join(' ');return `<div class="chart-wrap"><svg viewBox="0 0 620 215" class="chart" role="img" aria-label="Revenue trend from demo transactions">${[0,1,2,3].map(i=>`<line x1="45" y1="${30+i*48}" x2="585" y2="${30+i*48}"/><text x="0" y="${34+i*48}">${Math.round(max*(1-i/3)/1000)}k</text>`).join('')}<path d="${path} L573 180 L45 180Z" fill="#c4122f0e"/><path d="${path}" fill="none" stroke="#c4122f" stroke-width="3"/>${points.map((n,i)=>`<circle cx="${45+i*48}" cy="${175-n/max*145}" r="3" fill="#c4122f"><title>${money(n)}</title></circle>`).join('')}<text x="45" y="205">${date(db().now-U.period*D)}</text><text x="510" y="205">${date(db().now)}</text></svg></div>`}
function overviewPage(){const t=E.totals(U.store,U.period),members=E.segment('all').filter(c=>U.store==='all'||c.store===U.store),risk=members.filter(c=>E.customerDays(c)>=30),tiers=['Gold','Silver','Bronze'];return page('Good morning, Vikram.','Every customer interaction, connected to the next.',B('↧ Export','export','transactions')+B('＋ Create campaign','campaign-new','',true))+filterBar()+metrics([['Loyalty revenue',money(t.revenue),t.visits+' transactions'],['Active customers',number(t.members),members.length+' accessible profiles'],['Net contribution',money(t.margin),'Revenue minus item costs'],['Rewards redeemed',number(t.redemptions),'From completed transactions']])+`<div class="chart-grid">${panel('Loyalty is good for business.',revenueChart(),link('Explore reports →','analytics'))}${panel('Your customer community',tiers.map((tier,i)=>{const n=members.filter(c=>c.tier===tier).length;return `<div class="metric-row"><span>${tag(tier)}</span><strong>${n} members</strong></div><div class="progress"><span style="width:${n/(members.length||1)*100}%;opacity:${1-i*.25}"></span></div>`}).join('')+notice(`${risk.length} customers have not visited in 30 days.`),link('Explore audiences →','segments'))}</div><div class="bottom-grid">${panel('Campaigns making an impact',campaignTableX(db().campaigns.filter(c=>!c.archive).slice(0,4)),link('All campaigns →','campaigns'))}${panel('Your next best move',`<div class="insight-card"><div class="insight-tag">RETENTION OPPORTUNITY</div><h3>Reconnect with ${risk.length} customers.</h3><p>Use an audience based on actual visit history and consent.</p>${B('Create win-back campaign →','campaign-new','seg1')}</div><div class="insight-card plain-insight"><h3>Test the entire customer journey</h3><p>Run a purchase, issue points, apply offers, and inspect the resulting events.</p>${link('Open checkout simulator →','checkout')}</div>`)}</div><div class="store-strip">${panel('Every store. One connected community.',table(['STORE','TRANSACTIONS','REVENUE','CONTRIBUTION',''],db().stores.filter(s=>U.store==='all'||U.store===s.id).filter(s=>!E.role().stores.length||E.role().stores.includes(s.id)).map(s=>{const m=E.totals(s.id,U.period);return [e(s.name),m.visits,money(m.revenue),money(m.margin),B('View','store-detail',s.id)]})))}</div>`}
function customerPage(){let list=E.segment('all').filter(c=>(U.store==='all'||c.store===U.store)&&(U.tier==='all'||c.tier===U.tier)&&(c.name+' '+c.email+' '+c.tags.join(' ')).toLowerCase().includes(U.search.toLowerCase()));return page('People, not just points.','Profiles, consent, balances, and every moment in between.',B('Export profiles','export','customers')+B('＋ Add member','customer-new','',true))+`<div class="toolbar"><input id="x-search" class="search" aria-label="Search customers" placeholder="Search name, email or tags…" value="${e(U.search)}"><div class="filters"><select id="x-tier" aria-label="Tier">${['all','Gold','Silver','Bronze'].map(t=>`<option ${t===U.tier?'selected':''} value="${t}">${t==='all'?'All tiers':t}</option>`).join('')}</select><select id="x-store" aria-label="Store scope"><option value="all">All accessible stores</option>${sOptions().map(([id,n])=>`<option value="${id}" ${U.store===id?'selected':''}>${e(n)}</option>`).join('')}</select></div></div>`+metrics([['Matching members',list.length],['Reachable by email',list.filter(c=>c.consent.email&&c.status==='Active').length],['Total points',number(list.reduce((s,c)=>s+c.points,0))],['Stored value',money(list.reduce((s,c)=>s+c.wallet,0))]])+`<section class="panel">${table(['MEMBER','TIER','POINTS','VISITS','SPEND','STATUS',''],list.map(c=>[`<div class="customer-cell"><span class="avatar">${c.name.split(' ').map(n=>n[0]).join('')}</span><div><strong>${e(c.name)}</strong><span class="secondary">${e(c.email)}</span></div></div>`,tag(c.tier),number(c.points),c.visits,money(c.spent),tag(c.status),B('Open profile','customer-detail',c.id)]))}</section>`}
function profile(key){const c=E.find('customers',key);show(e(c.name),`<div class="profile-summary"><span class="avatar">${c.name.split(' ').map(n=>n[0]).join('')}</span><div><h3>${e(c.email)}</h3><p class="subtitle">${e(E.find('stores',c.store).name)} · ${tag(c.tier)} ${tag(c.status)}</p></div></div><div class="inline-metrics"><div>Points<strong>${number(c.points)}</strong>Available</div><div>Lifetime spend<strong>${money(c.spent)}</strong>${c.visits} visits</div><div>Last visit<strong>${E.customerDays(c)} days</strong>${E.smart(c)}</div></div><div class="actions">${B('Edit profile & consent','customer-edit',c.id)}${B('Adjust points','points',c.id)}${B('Member experience','member-open',c.id)}</div><h3 class="section-title">Activity & point ledger</h3>${table(['DATE','ACTIVITY','POINTS'],c.ledger.slice(0,12).map(l=>[date(l.date),e(l.reason),`<strong class="${l.points>=0?'positive':'negative'}">${l.points>0?'+':''}${l.points}</strong>`]))}<h3 class="section-title">Available gifted rewards</h3>${c.issued.filter(g=>!g.used).map(g=>`<div class="metric-row">${e(E.find('offers',g.offer).name)}<span class="secondary">${e(g.reason)}</span></div>`).join('')||'<p class="subtitle">No unused gifted rewards.</p>'}<h3 class="section-title">Communication preferences</h3><div class="chip-row">${Object.entries(c.consent).map(([k,v])=>tag(k+': '+(v?'opted in':'opted out'))).join('')}</div>`,true)}
function memberForm(key){const c=key?E.find('customers',key):{name:'',email:'',store:'s0',birthday:'1992-09-16',consent:{email:true,sms:false,push:true},tags:[]};show(key?'Edit member':'Enroll a new member',form(key?'customer-edit':'customer-new',`<div class="form-grid">${input('Full name','name',c.name,'text','required')}${input('Email','email',c.email,'email','required')}${select('Home store','store',sOptions(),c.store)}${input('Birthday','birthday',c.birthday,'date','required')}${key?input('Tags (comma separated)','tags',c.tags.join(', ')):select('Referred by','referrer',[['','No referral'],...cOptions()],'')}</div><h3 class="section-title">Consent recorded for each channel</h3><div class="chip-row">${['email','sms','push'].map(k=>check(k[0].toUpperCase()+k.slice(1),'consent_'+k,c.consent[k])).join('')}</div>${notice('Enrollment does not require marketing consent. Unsubscribed channels are excluded from delivery.')}`,key?'Save member':'Enroll member',key||''))}
function ruleRow(r={},ex=false){return `<div class="rule-row ${ex?'exclude-rule':''}">${select('Attribute','field',[['days','Days since visit'],['visits','Visit count'],['spent','Lifetime spend'],['points','Points'],['tier','Tier'],['store','Home store ID'],['tags','Tags'],['status','Account status']],r.field||'days')}${select('Operator','op',[['gte','At least'],['lte','At most'],['eq','Equals'],['neq','Does not equal'],['contains','Contains']],r.op||'gte')}${input('Value','value',r.value??30,'text','required')}${B('×','remove-rule')}</div>`}
function segmentForm(key){const s=key?E.find('segments',key):{name:'',logic:'AND',rules:[{field:'days',op:'gte',value:30}],exclude:[],tags:[]};show(key?'Edit audience':'Build an audience',form('segment',input('Audience name','name',s.name,'text','required')+select('Match rules','logic',['AND','OR'],s.logic)+`<div id="segment-rules">${s.rules.map(r=>ruleRow(r)).join('')}</div>${B('＋ Add rule','add-rule')}<h3 class="section-title">Exclude customers matching any rule</h3><div id="exclude-rules">${s.exclude.map(r=>ruleRow(r,true)).join('')}</div>${B('＋ Add exclusion','add-exclusion')}${input('Tags','tags',s.tags.join(', '))}<div class="notice" id="segment-preview">Preview this audience before saving.</div>${B('Preview reachability','preview-segment')}`,'Save audience',key||''),true)}
function segmentPage(){return page('Find the people behind the patterns.','Live audiences, consent-aware reach, and smart customer groups.',B('＋ Build audience','segment-new','',true))+tabs([['segments','Your audiences'],['smart','Smart segments'],['reach','Channel reachability']])+(tabIs('segments','segments')?`<section class="panel">${table(['AUDIENCE','MEMBERS','EMAIL / SMS / PUSH','MODE',''],db().segments.map(s=>[e(s.name)+'<span class="secondary">'+s.rules.length+' rules · '+s.logic+'</span>',E.segment(s.id).length,["Email","SMS","Push"].map(c=>E.reachable(s.id,c).length).join(' / '),tag(s.frozen?'Frozen':'Dynamic'),`<div class="row-actions">${B('Edit','segment-edit',s.id)}${B(s.frozen?'Unfreeze':'Freeze','segment-freeze',s.id)}${B('Campaign','campaign-new',s.id)}</div>`]))}</section>`:tabIs('smart','segments')?`<div class="cards">${E.smartNames.map(name=>{let list=E.segment('smart:'+name);return `<section class="panel padded"><span class="insight-tag">BEHAVIORAL AUDIENCE</span><h2>${name}</h2><div class="big-number">${list.length}<span class="subtitle"> members</span></div><p class="subtitle">Avg spend ${money(list.reduce((s,c)=>s+c.spent,0)/(list.length||1))}</p><div class="reward-footer">${B('View members','smart-detail',name)}${B('Campaign →','campaign-new','smart:'+name)}</div></section>`}).join('')}</div>${notice('Ember demo groups recalculate immediately from local activity. These are transparent rules, not a trained predictive model.')}`:panel('Reachability by audience',table(['AUDIENCE','TOTAL','EMAIL','SMS','PUSH','NO CHANNEL'],[{id:'all',name:'All members'},...db().segments].map(s=>{const list=E.segment(s.id);return [e(s.name),list.length,...['Email','SMS','Push'].map(c=>E.reachable(s.id,c).length),list.filter(c=>!Object.values(c.consent).some(Boolean)||c.status!=='Active').length]}))))}
function programPage(){const p=db().program;return page('Reward every kind of loyalty.','Earning, tiers, redemption rules, and expiry share one engine.',B('Member preview','member-open',U.selected))+form('program',`<div class="settings-grid">${panel('Earning model',select('Program type','mode',['Banked points','Visit based','Points to rewards','Points to currency'],p.mode)+`<div class="form-grid">${input('Points per ₹100','earn',p.earn,'number','min="0" max="1000" required')}${input('Daily earning cap','dailyCap',p.dailyCap,'number','min="1" required')}${input('Visit goal','visitGoal',p.visitGoal,'number','min="1" required')}${input('Conversion threshold','threshold',p.threshold,'number','min="1" required')}${input('Currency per point','currencyRate',p.currencyRate,'number','min="0.01" max="10" step="0.01" required')}${input('Points expire after (days)','expiryDays',p.expiryDays,'number','min="1" required')}</div>`+select('Milestone reward','baseOffer',oOptions(),p.baseOffer))}${panel('Tiers & redemption',`<div class="form-grid">${input('Silver qualifying points','tierSilver',p.tierSilver,'number','min="1" required')}${input('Gold qualifying points','tierGold',p.tierGold,'number','min="1" required')}${input('Silver multiplier','silverMultiplier',p.silverMultiplier,'number','min="1" max="5" step="0.05" required')}${input('Gold multiplier','goldMultiplier',p.goldMultiplier,'number','min="1" max="5" step="0.05" required')}${input('Rewards per transaction','maxRedemptions',p.maxRedemptions,'number','min="1" max="10" required')}</div>`+check('Allow compatible discounts to stack','stacking',p.stacking)+check('Lock basket until checkout','lock',p.lock)+notice('Tier qualification uses lifetime earned points. Earning and redemption are applied during checkout; the simulation clock processes expiry.'))}</div>`,'Save program')}
function offerForm(key){const o=key?E.find('offers',key):{name:'',kind:'Fixed discount',value:100,points:250,minSpend:0,category:'Any',product:'Any',tier:'Any',stores:[],max:250,active:true,auto:false,stackable:true,priority:2,expiry:db().now+90*D,desc:''};show(key?'Edit reward & eligibility':'Create reward & offer',form('offer',input('Name','name',o.name,'text','required')+area('Description','desc',o.desc)+`<div class="form-grid">${select('Benefit','kind',['Fixed discount','Percentage','Free item','BOGO','Buy X Get Y','Promotional price','Rate rollback'],o.kind)}${input('Benefit value','value',o.value,'number','min="0" step="0.01" required')}${input('Points cost','points',o.points,'number','min="0" required')}${input('Minimum basket','minSpend',o.minSpend,'number','min="0" required')}${select('Category','category',['Any','Drinks','Food','Bakery','Retail'],o.category)}${select('Product','product',[['Any','Any product'],...options(db().products)],o.product)}${select('Tier','tier',['Any','Bronze','Silver','Gold'],o.tier)}${select('Eligible store','store',[['all','All stores'],...sOptions()],o.stores[0]||'all')}${input('Maximum discount','max',o.max,'number','min="1" required')}${input('Processing priority','priority',o.priority,'number','min="1" max="10" required')}${input('Valid until','expiry',new Date(o.expiry).toISOString().slice(0,10),'date','required')}${select('Exclude category','exclude',['None','Retail','Drinks','Bakery','Food'],o.exclude||'None')}</div><div class="chip-row">${check('Automatically apply','auto',o.auto)}${check('Can stack with other offers','stackable',o.stackable)}${check('Active','active',o.active)}</div>`,'Save offer',key||''),true)}
function rewardsPage(){return page('Small rewards. Smarter rules.','Offers, coupons, and dynamic gifts—ready to test at checkout.',B('＋ Create offer','offer-new','',true))+tabs([['catalog','Reward catalog'],['coupons','Coupons & promos'],['dynamic','Dynamic rewards'],['products','Product catalog']])+(tabIs('catalog','catalog')?`<div class="cards">${db().offers.map((o,i)=>`<article class="panel reward-card"><div class="reward-visual" style="${i%2?'background:#f1f3f8;color:#586583':''}">${o.kind==='Percentage'?o.value+'%':o.kind==='BOGO'?'1 + 1':o.kind==='Buy X Get Y'?'2 + 1':o.kind==='Free item'?'ON US':money(o.value)}</div><div class="chip-row">${tag(o.active?'Active':'Paused')} ${tag(o.kind)}</div><h2 style="margin-top:16px">${e(o.name)}</h2><p>${e(o.desc)}</p><div class="metric-row"><span>${o.points} points</span><span>${o.used} redeemed</span></div><p class="secondary">${o.tier==='Any'?'All tiers':o.tier} · Min ${money(o.minSpend)} · ${o.stackable?'Stackable':'No stacking'}</p><div class="reward-footer">${B('Edit','offer-edit',o.id)}${B(o.active?'Pause':'Activate','offer-toggle',o.id)}${B('Test →','offer-test',o.id)}</div></article>`).join('')}</div>`:tabIs('coupons','catalog')?panel('Codes that bring customers back',table(['CODE','TYPE','OFFER','USED / LIMIT','EXPIRY','STATUS'],db().coupons.map(c=>[e(c.code),e(c.type),e(E.find('offers',c.offer).name),c.used+' / '+c.limit,date(c.expires),tag(c.expires<db().now?'Expired':c.active?'Active':'Paused')])),`<div class="actions">${B('Export codes','export','coupons')}${B('Generate codes','codes','',true)}</div>`):tabIs('dynamic','catalog')?panel('Conditional and surprise gifts',table(['RULE','METHOD','LOGIC',''],db().dynamicRules.map(r=>[e(r.name),r.mode,r.mode==='Conditional'?'Spend ≥ '+money(r.threshold):r.weight+'% / '+(100-r.weight)+'% split',B('Issue demo gift','dynamic-issue',r.id)])),B('Create rule','dynamic-new','',true)):panel('Products synced for offer qualification',table(['PRODUCT','CATEGORY','PRICE','UNIT COST'],db().products.map(p=>[e(p.name),p.category,money(p.price),money(p.cost)])),B('Add product','product-new','',true)))}
function campaignTableX(list){return table(['CAMPAIGN','CHANNEL','STATUS','REACH',''],list.map(c=>[e(c.name)+`<span class="secondary">${e(c.tags?.join(' · ')||'Campaign')}</span>`,c.channel,tag(c.archive?'Archived':c.status),E.campaignReach(c).length,B('Open','campaign-detail',c.id)]))}
function campaignFormX(segment='all',key){const c=key?E.find('campaigns',key):{name:segment==='seg1'?'A warm welcome back':'',channel:'Email',segment:segment||'all',message:'Hi {{first_name}}, your next favorite moment is waiting. Enjoy a reward on your next visit.',messageB:'Your next visit, made sweeter. Come back for a little reward.',offer:'o1',ab:false,control:10,budget:8000,tags:[],repeat:0};show('Build a campaign',form('campaign',input('Campaign name','name',c.name,'text','required')+`<div class="form-grid">${select('Channel','channel',['Email','SMS','Push'],c.channel)}${select('Audience','segment',[['all','All members'],...options(db().segments),...E.smartNames.map(n=>['smart:'+n,n])],c.segment)}${select('Store scope','store',[['','All accessible stores'],...sOptions()],c.store||'')}${select('Offer','offer',[['none','Message only'],...oOptions()],c.offer)}</div>`+area('Message A','message',c.message)+check('Run an A/B test','ab',c.ab)+area('Message B','messageB',c.messageB,'')+`<div class="form-grid">${input('Control group (%)','control',c.control,'number','min="0" max="50" required')}${input('Campaign budget (₹)','budget',c.budget,'number','min="0" required')}${input('Scheduled launch (optional)','scheduled','','datetime-local')}${select('Repeat','repeat',[[0,'One time'],[7,'Every 7 days'],[30,'Every 30 days']],c.repeat)}</div>`+input('Tags (comma separated)','tags',c.tags.join(', '))+check('Submit for approval','submit',true)+notice('Audience reach is calculated from consent, store scope, account status, and frequency caps. Owner approval is required before delivery.')+B('Preview audience','campaign-reach'),'Save campaign',key||''),true)}
function campaignPage(){const list=db().campaigns.filter(c=>U.campaignStatus==='Archived'?c.archive:!c.archive&&(U.campaignStatus==='All'||c.status===U.campaignStatus));return page('Make your next message matter.','From the right audience to a measurable outcome.',B('＋ Create campaign','campaign-new','all',true))+metrics([['Delivered in demo',db().campaigns.reduce((n,c)=>n+(c.delivered||0),0)],['Awaiting approval',db().campaigns.filter(c=>c.status==='Pending approval').length],['Attributed revenue',money(db().campaigns.reduce((n,c)=>n+(c.revenue||0),0))],['Scheduled',db().campaigns.filter(c=>c.status==='Scheduled').length]])+`<div class="tab-row">${['All','Draft','Pending approval','Approved','Scheduled','Completed','Archived'].map(t=>`<button class="${U.campaignStatus===t?'selected':''}" data-do="campaign-filter" data-id="${t}">${t}</button>`).join('')}</div><section class="panel">${campaignTableX(list)}</section>`+notice('Delivery records are generated locally. Emails, SMS, and push messages are not transmitted. Scheduled runs execute when you advance the simulation clock.');}
function campaignDetail(key){const c=E.find('campaigns',key),actions=[];if(['Draft','Disapproved'].includes(c.status))actions.push('Edit','Submit');if(c.status==='Pending approval')actions.push('Approve','Reject');if(c.status==='Approved')actions.push('Launch');if(['Scheduled','Active'].includes(c.status))actions.push('Pause');if(c.status==='Paused')actions.push('Resume');actions.push('Duplicate');if(!['Active','Scheduled','Pending approval'].includes(c.status)&&!c.archive)actions.push('Archive');show(e(c.name),`${tag(c.status)}<div class="inline-metrics"><div>Eligible now<strong>${E.campaignReach(c).length}</strong>Consent + cap applied</div><div>Delivered<strong>${c.delivered||0}</strong>Local simulation</div><div>Revenue<strong>${money(c.revenue||0)}</strong>${c.conversions||0} purchases</div></div><div class="notice">${e(c.message)}</div>${c.ab?notice('<strong>Variant B:</strong> '+e(c.messageB)):''}<div class="metric-row">Control group<strong>${c.control}%</strong></div><div class="metric-row">Budget<strong>${money(c.budget)}</strong></div><div class="metric-row">Schedule<strong>${c.scheduled?time(c.scheduled):'Launch when approved'}${c.repeat?' · Every '+c.repeat+' days':''}</strong></div><div class="actions wrap" style="margin:18px 0">${actions.map(a=>B(a,'campaign-action',key+'|'+a,a==='Launch'||a==='Approve')).join('')}</div><h3 class="section-title">Delivery and holdout records</h3>${table(['MEMBER','VARIANT','STATE'],(c.deliveries||[]).map(d=>[e(E.find('customers',d.customer).name),d.group,tag(d.status)]))}`,true)}
function journeyPage(){return page('Always there at the right moment.','Event triggers, rewards, and delayed follow-ups that you can run.',B('Simulate event','event-sim')+B('＋ Create journey','journey-new','',true))+db().journeys.map(j=>`<section class="panel padded" style="margin-bottom:20px"><div class="section-heading"><div><h2>${e(j.name)}</h2><p class="subtitle">${j.enrolled} enrollments · ${tag(j.active?'Active':'Paused')}</p></div><div class="actions">${B('Edit','journey-edit',j.id)}${B(j.active?'Pause':'Activate','journey-toggle',j.id)}</div></div><div class="journey"><div class="node"><small>TRIGGER</small>${j.trigger}</div><b>→</b><div class="node"><small>DELAY</small>${j.delay} days</div><b>→</b><div class="node accent-node"><small>ACTION</small>${j.action==='Points'?j.value+' points':j.action==='Offer'?e(E.find('offers',j.offer).name):j.action}</div><b>→</b><div class="node"><small>FOLLOW-UP</small>${j.follow} after ${j.followDelay} days</div></div></section>`).join('')+panel('Journey execution queue',table(['MEMBER','JOURNEY','STEP','DUE','STATUS'],db().jobs.slice(-20).reverse().map(j=>[e(E.find('customers',j.customer).name),e(E.find('journeys',j.journey).name),j.kind,time(j.due),tag(j.status)])),B('Advance clock','clock'))}
function checkoutPage(){const b=U.basket,q=U.quote;return page('One basket. Every benefit.','Test earning, offers, membership perks, payment, and refunds together.',B('Recent receipts','receipt-list'))+`<div class="checkout-grid"><section class="panel padded"><form data-form="checkout-preview"><div class="form-grid">${select('Member','customer',cOptions(),b.customer)}${select('Store','store',sOptions(),b.store)}${select('Channel','channel',['In store','App','Web','Drive-through','Kiosk'],b.channel)}${select('Payment','payment',['External demo','Stored value'],b.payment)}</div><h3 class="section-title">Basket items</h3><div id="basket-lines">${b.lines.map(l=>`<div class="basket-line">${select('Product','product',options(db().products),l.product)}${input('Quantity','qty',l.qty,'number','min="1" max="99" required')}${B('×','basket-remove')}</div>`).join('')}</div>${B('＋ Add item','basket-add')}<h3 class="section-title">Choose rewards</h3><div class="offer-options">${db().offers.filter(o=>o.active&&!o.auto).map(o=>check(`${e(o.name)} <small>${o.points} pts</small>`,'offer_'+o.id,b.offers.includes(o.id))).join('')}</div><p class="secondary">Automatic offers and membership perks are evaluated at preview.</p><div class="form-grid">${input('Coupon / promo code','code',b.code)}${input('Unique receipt reference','reference',b.reference,'text','required')}${select('Attribute to campaign','campaign',[['','No campaign'],...options(db().campaigns.filter(c=>c.status==='Completed'))],b.campaign)}</div><button class="primary" type="submit">Evaluate basket →</button><p class="form-error" role="alert"></p></form></section><section class="panel padded sticky-summary"><h2>Transaction preview</h2>${q?`<div class="metric-row">Subtotal<strong>${money(q.gross)}</strong></div>${q.applied.map(a=>`<div class="metric-row"><span>${e(a.name)}<small class="secondary">${a.points} points</small></span><strong>−${money(a.discount)}</strong></div>`).join('')}${q.memberBenefits.map(a=>`<div class="metric-row">${e(a.name)}<strong>−${money(a.discount)}</strong></div>`).join('')}${q.currencyCost?`<div class="metric-row">Loyalty currency<strong>−${money(q.currencyCost)}</strong></div>`:''}<div class="metric-row"><h2>Total</h2><h2>${money(q.net)}</h2></div><div class="metric-row">Points earned<strong>+${q.points}</strong></div><div class="metric-row">Points spent<strong>${q.pointCost}</strong></div><div class="metric-row">Contribution<strong>${money(q.net-q.cost)}</strong></div>${q.rejected.length?notice(q.rejected.map(e).join('<br>')):''}<p class="secondary">${db().program.lock?'Basket lock enabled. Changed inputs require a new preview.':'Basket recalculated at checkout.'}</p>${B('Complete demo checkout','checkout-commit','',true)}`:empty('Ready when you are.','Choose a member, add products, and evaluate the basket.')}${notice('Payment is simulated. No card or bank information is collected.')}</section></div>`}
function membershipPage(){return page('Membership has its benefits.','Paid plans, renewals, benefit limits, and cancellation insights.',B('Enroll member','membership-enroll')+B('＋ Create plan','plan-new','',true))+tabs([['plans','Plans'],['members','Subscriptions'],['activity','Billing activity']])+(tabIs('plans','plans')?`<div class="cards">${db().plans.map(p=>`<section class="panel padded"><span class="badge">${p.active?'Active plan':'Paused'}</span><h2 style="margin-top:18px">${e(p.name)}</h2><div class="big-number">${money(p.price)}<span class="subtitle"> / ${p.days} days</span></div><p>${p.benefit}% off ${p.category==='Any'?'eligible purchases':p.category.toLowerCase()}</p><div class="metric-row">Uses per period<strong>${p.maxUses}</strong></div><div class="metric-row">Uses per day<strong>${p.dailyUses}</strong></div><div class="reward-footer">${B('Edit','plan-edit',p.id)}${B(p.active?'Pause':'Activate','plan-toggle',p.id)}</div></section>`).join('')}</div>`:tabIs('members','plans')?panel('Member subscriptions',table(['MEMBER','PLAN','RENEWAL','BENEFITS USED','STATUS',''],db().memberships.map(m=>[e(E.find('customers',m.customer).name),e(E.find('plans',m.plan).name),date(m.renews),m.uses.length,tag(m.status),m.status==='Active'?B('Cancel','membership-cancel',m.id):e(m.cancelReason)]))):panel('Simulated billing and renewals',table(['DATE','MEMBER','EVENT','AMOUNT'],db().walletEvents.filter(x=>x.type.includes('Membership')).map(x=>[time(x.date),e(E.find('customers',x.customer).name),e(x.type),money(Math.abs(x.amount))]))))+notice('Membership billing is simulated. Benefits are applied at checkout; renewals run when the simulation clock advances.')}
function walletPage(){const c=E.find('customers',U.selected);return page('A member experience worth coming back to.','Preview the app, wallet pass, consent, and loyalty payment flow.')+`<div class="toolbar"><select id="x-member" aria-label="Preview member">${cOptions().map(([id,n])=>`<option value="${id}" ${id===U.selected?'selected':''}>${e(n)}</option>`).join('')}</select><div class="actions">${B('Enroll member','customer-new')}${B('Simulate login','auth',c.id)}</div></div><div class="member-grid"><section class="phone-preview"><div class="phone-brand">ember <span>MOD REWARDS</span></div><p>Hello, ${e(c.name.split(' ')[0])}.</p><div class="member-card"><span>${c.tier.toUpperCase()} MEMBER</span><h1>${number(c.points)} points</h1><small>${number(c.lifetime)} lifetime qualifying points</small><div class="progress"><span style="width:${Math.min(100,c.lifetime/db().program.tierGold*100)}%;background:white"></span></div></div><div class="metric-row">Your stored value<strong>${money(c.wallet)}</strong></div><div class="member-token">${c.pass?.code||'EMBER-'+c.id.toUpperCase()}<small>Demo identification token · no live payment</small></div><div class="actions wrap">${B('Earn & pay','member-checkout',c.id,true)}${B('Add value','wallet-topup',c.id)}</div><h3 class="section-title">Available rewards</h3>${db().offers.filter(o=>o.active&&(o.tier==='Any'||o.tier===c.tier)).slice(0,3).map(o=>`<div class="metric-row"><span>${e(o.name)}</span><strong>${o.points} pts</strong></div>`).join('')}</section><div>${panel('Digital wallet pass',`<p class="subtitle">${c.pass?'Issued for '+c.pass.platform:'Choose a wallet to preview a member pass.'}</p><div class="actions wrap" style="margin-top:20px">${B('Apple Wallet preview','pass',c.id+'|Apple Wallet')}${B('Google Wallet preview','pass',c.id+'|Google Wallet')}${c.pass?B('Download pass data','pass-download',c.id):''}</div>${notice('This local pass is a preview and JSON download, not a signed .pkpass or Google Wallet integration.')}`)}<div class="store-strip">${panel('Stored value preferences',form('wallet-prefs',check('Enable simulated auto-reload','autoReload',c.autoReload)+`<div class="form-grid">${input('Reload below (₹)','reloadThreshold',c.reloadThreshold,'number','min="0" max="5000" required')}${input('Reload amount (₹)','reloadAmount',c.reloadAmount,'number','min="100" max="10000" required')}</div>`,'Save preferences',c.id))}</div><div class="store-strip">${panel('Recent wallet activity',table(['EVENT','AMOUNT'],db().walletEvents.filter(w=>w.customer===c.id).slice(0,5).map(w=>[e(w.type),money(w.amount)])))}</div></div></div>`}
function engagementPage(){return page('Give people a reason to participate.','Challenges, feedback, referrals, causes, and games with real demo rewards.')+tabs([['challenges','Challenges'],['surveys','Surveys'],['referrals','Referrals'],['causes','Social causes'],['games','Games']])+(tabIs('challenges','challenges')?panel('Visit and category challenges',table(['CHALLENGE','GOAL','REWARD','COMPLETIONS',''],db().challenges.map(c=>[e(c.name),c.goal+' '+c.category+' visits',c.reward+' points',c.claimed.length,B('Progress','challenge-progress',c.id)])),B('Create challenge','challenge-new','',true)):tabIs('surveys','challenges')?panel('Listen, learn, and reward',table(['SURVEY','RESPONSES','AVERAGE SCORE','REWARD',''],db().surveys.map(s=>[e(s.name),s.responses.length,s.responses.length?(s.responses.reduce((n,r)=>n+r.rating,0)/s.responses.length).toFixed(1)+'/10':'No responses yet',s.reward+' points',B('Respond in demo','survey',s.id)])),B('Create survey','survey-new','',true)):tabIs('referrals','challenges')?panel('Word of mouth, rewarded',notice('Both members receive 200 points after the referred member’s first purchase. Referrers are capped at five rewarded referrals per 30 days.')+table(['REFERRER','NEW MEMBER','STATUS','DATE'],db().referrals.map(r=>[e(E.find('customers',r.referrer).name),e(E.find('customers',r.customer).name),tag(r.status),date(r.date)])),B('Enroll a referred member','customer-new','',true)):tabIs('causes','challenges')?panel('Turn points into purpose',table(['CAUSE','POINTS DONATED','DONATIONS',''],db().causes.map(c=>[e(c.name),number(c.points),c.donations,B('Donate points','donate',c.id)])),B('Add cause','cause-new','',true)):panel('A little surprise, every day',db().games.map(g=>`<div class="section-heading"><div><h2>${e(g.name)}</h2><p class="subtitle">${g.dailyPlays} plays / member / day · ${g.stock} prize awards remaining</p></div><div class="actions">${B('Configure','game-edit',g.id)}${B('Play in demo','game-play',g.id,true)}</div></div><div class="prize-grid">${g.prizes.map(p=>`<div><strong>${e(p.name)}</strong><span>${p.weight}% weight</span></div>`).join('')}</div>`).join('')+table(['WHEN','MEMBER','PRIZE'],db().plays.slice(0,10).map(p=>[time(p.date),e(E.find('customers',p.customer).name),e(p.prize)]))))}
function merchandisePage(){return page('Loyalty you can hold.','Manage merchandise, variants, inventory, and fulfillment.',B('＋ Add merchandise','swag-new','',true))+tabs([['catalog','Merchandise catalog'],['orders','Fulfillment queue']])+(tabIs('catalog','catalog')?`<div class="cards">${db().swag.map(s=>`<section class="panel reward-card"><div class="reward-visual">${s.sku}</div><h2>${e(s.name)}</h2><div class="big-number">${number(s.points)} <span class="subtitle">points</span></div>${Object.entries(s.variants).map(([v,n])=>`<div class="metric-row">${e(v)}<strong>${n} in stock</strong></div>`).join('')}<div class="reward-footer">${B('Edit inventory','swag-edit',s.id)}${B('Redeem','swag-redeem',s.id,true)}</div></section>`).join('')}</div>`:panel('Orders and shipping details',table(['ORDER','MEMBER','ITEM / VARIANT','METHOD','STATUS',''],db().orders.map(o=>[o.id,e(E.find('customers',o.customer).name),e(E.find('swag',o.item).name)+' / '+e(o.variant),e(o.fulfillment),tag(o.status),o.status==='Pending'?B('Fulfill','fulfill',o.id):'Completed'])),B('Export orders','export','orders')))}
function storePage(){return page('Local favorites. Connected operations.','Store groups, franchise access, POS status, and receipts.',B('＋ Add store','store-new','',true))+`<div class="cards">${db().stores.map(s=>{const m=E.totals(s.id,30);return `<section class="panel padded"><div class="section-heading"><span class="stat-icon">${icon('stores')}</span>${tag(s.enabled?'Operational':'Disabled')}</div><h2 class="section-title">${e(s.name)}</h2><p class="subtitle">${e(s.city)} · ${s.id.toUpperCase()}</p><div class="metric-row">Group<strong>${e(s.group)}</strong></div><div class="metric-row">Revenue<strong>${money(m.revenue)}</strong></div><div class="metric-row">POS<strong>${e(s.pos)}</strong></div><div class="reward-footer">${B('Configure','store-edit',s.id)}${B('View dashboard','store-dashboard',s.id)}</div></section>`}).join('')}</div>`}
function analyticsPage(){const m=E.totals(U.store,U.period);return page('The story behind your growth.','Reports calculated from the same transactions that drive your loyalty program.',B('Export transactions','export','transactions'))+filterBar()+metrics([['Net revenue',money(m.revenue)],['Average order',money(m.revenue/(m.visits||1))],['Offer cost',money(m.discount)],['Contribution margin',pct(m.margin/(m.revenue||1)*100)]])+tabs([['performance','Program performance'],['campaigns','Campaign & offer reports'],['cohorts','Retention & cohorts'],['monthly','Month-on-month']])+(tabIs('performance','performance')?`<div class="chart-grid">${panel('Revenue over time',revenueChart())}${panel('Revenue by channel',['In store','App','Web','Drive-through','Kiosk'].map(channel=>{let n=m.rows.filter(t=>t.channel===channel).reduce((s,t)=>s+t.net,0);return `<div class="metric-row">${channel}<strong>${money(n)}</strong></div><div class="progress"><span style="width:${n/(m.revenue||1)*100}%"></span></div>`}).join(''))}</div>${panel('Top-selling products',table(['PRODUCT','UNITS','GROSS ITEM VALUE'],db().products.map(p=>{let n=m.rows.reduce((s,t)=>s+t.lines.filter(l=>l.product===p.id).reduce((s,l)=>s+l.qty,0),0);return [e(p.name),n,money(n*p.price)]})))}`:tabIs('campaigns','performance')?panel('Campaign outcomes',table(['CAMPAIGN','DELIVERED','CONVERSIONS','REVENUE','HOLDOUT'],db().campaigns.map(c=>[e(c.name),c.delivered||0,c.conversions||0,money(c.revenue||0),(c.deliveries||[]).filter(d=>d.group==='Control').length])))+`<div class="store-strip">${panel('Redeemable performance',table(['REWARD','REDEMPTIONS','DISCOUNT'],db().offers.map(o=>{let ts=m.rows.filter(t=>t.offers.includes(o.id));return [e(o.name),ts.length,money(ts.reduce((n,t)=>n+(t.quote?.applied.find(a=>a.id===o.id)?.discount||t.discount),0))]})))}</div>`:tabIs('cohorts','performance')?panel('Visit recency cohorts',table(['LAST VISIT','CUSTOMERS','LIFETIME SPEND','REACHABLE EMAIL'],[[0,7],[8,30],[31,60],[61,90],[91,365],[366,10000]].map(([a,b])=>{const cs=E.segment('all').filter(c=>E.customerDays(c)>=a&&E.customerDays(c)<=b);return [`${a}–${b===10000?'∞':b} days`,cs.length,money(cs.reduce((s,c)=>s+c.spent,0)),cs.filter(c=>c.consent.email).length]}))):panel('Monthly revenue and visits',table(['MONTH','REVENUE','VISITS','ACTIVE MEMBERS','DISCOUNT'],Array.from({length:6},(_,i)=>{let d=new Date(db().now);d.setUTCMonth(d.getUTCMonth()-i,1);d.setUTCHours(0,0,0,0);let start=+d;d.setUTCMonth(d.getUTCMonth()+1);let ts=db().transactions.filter(t=>t.status==='Completed'&&t.date>=start&&t.date<+d&&(U.store==='all'||t.store===U.store));return [new Date(start).toLocaleDateString('en-IN',{month:'long',year:'numeric'}),money(ts.reduce((s,t)=>s+t.net,0)),ts.length,new Set(ts.map(t=>t.customer)).size,money(ts.reduce((s,t)=>s+t.discount,0))]}))))}
function fraudPage(){return page('Protect the trust you’ve earned.','Rule-based detection, clear evidence, and reviewable decisions.',B('＋ Create rule','fraud-rule-new','',true))+metrics([['Open cases',db().fraudCases.filter(f=>f.status==='Open').length],['Frozen members',db().customers.filter(c=>c.status==='Frozen').length],['Active rules',db().fraudRules.filter(r=>r.active).length],['Resolved cases',db().fraudCases.filter(f=>f.status!=='Open').length]])+tabs([['cases','Investigation queue'],['rules','Detection rules']])+(tabIs('cases','cases')?panel('Flagged activity',table(['MEMBER','RULE','EVIDENCE','STATUS',''],db().fraudCases.map(f=>[e(E.find('customers',f.customer).name),e(E.find('fraudRules',f.rule).name),e(f.evidence),tag(f.status),B('Investigate','fraud-detail',f.id)])),B('Generate test case','fraud-sim')):panel('Rules applied to local events',table(['RULE','TRIGGER','THRESHOLD','STATUS',''],db().fraudRules.map(r=>[e(r.name),r.type,r.threshold,tag(r.active?'Active':'Paused'),`${B('Edit','fraud-rule-edit',r.id)} ${B(r.active?'Pause':'Activate','fraud-rule-toggle',r.id)}`]))))}
function integrationsPage(){return page('Everything, connected.','Configure adapters and inspect delivery behavior without sending data.',B('＋ Add adapter','adapter-new','',true))+tabs([['adapters','Connections'],['outbox','Outbound events'],['inbound','Inbound simulator']])+(tabIs('adapters','adapters')?`<div class="cards">${db().adapters.map(a=>`<section class="panel padded"><div class="section-heading"><h2>${e(a.name)}</h2>${tag(a.active?'Active':'Paused')}</div><p class="subtitle">${e(a.kind)}</p><p class="code-line">${e(a.url)}</p><div class="metric-row">Delivery simulator<strong>${a.failure?'503 failure':'200 success'}</strong></div><p class="secondary">${a.events.map(e).join(', ')}</p><div class="row-actions">${B('Configure','adapter-edit',a.id)}${B('Send test','adapter-test',a.id)}${B(a.active?'Pause':'Activate','adapter-toggle',a.id)}</div></section>`).join('')}</div>`:tabIs('outbox','adapters')?panel('Delivery logs & retries',table(['EVENT','ADAPTER','STATUS','ATTEMPTS','RESPONSE',''],db().outbox.slice(0,40).map(x=>[e(x.type),e(E.find('adapters',x.adapter).name),tag(x.status),x.attempts,e(x.response),`${B('Payload','event-payload',x.id)} ${x.status==='Failed'?B('Retry','event-retry',x.id):''}`]))):panel('Replay a partner award',form('inbound',`<div class="form-grid">${select('Member','customer',cOptions(),U.selected)}${input('Points','points',100,'number','min="1" max="1000" required')}${input('Unique event reference','reference','partner-'+(db().seq+1),'text','required')}</div>`+notice('Replaying the same reference is rejected to prevent duplicate awards.'),'Process local event')))+notice('No network requests are made. Production adapters require API credentials, provider contracts, and server-side delivery workers.')}
function dataPage(){return page('Your data, on your terms.','Field-level exports, local schedules, and portable workspace backups.',B('Download backup','backup')+B('Restore backup','restore'))+tabs([['export','Export builder'],['schedules','Scheduled exports'],['history','Export history']])+(tabIs('export','export')?panel('Build a CSV export',form('export',select('Dataset','dataset',[['customers','Customers'],['transactions','Transactions'],['campaigns','Campaigns'],['offers','Offers'],['coupons','Coupon codes'],['orders','Merchandise orders'],['audit','Audit trail']],U.dataset||'transactions','id="export-dataset"')+`<div id="export-fields" class="field-checks">${exportFields(U.dataset||'transactions')}</div>`+check('Save as recurring export','recurring',false)+`<div class="form-grid">${input('Schedule name','name','Weekly performance')}${select('Cadence','cadence',[[1,'Daily'],[7,'Weekly'],[30,'Monthly']],7)}</div>`,'Download CSV')):tabIs('schedules','export')?panel('Local export schedules',table(['SCHEDULE','DATASET','CADENCE','NEXT RUN',''],db().exportJobs.map(j=>[e(j.name),j.dataset,j.cadence+' days',date(j.next),B(j.active?'Pause':'Activate','export-toggle',j.id)])),B('Run due jobs','clock')):panel('Prepared reports',table(['REPORT','DATASET','ROWS','CREATED',''],db().exportHistory.map(h=>[e(h.job),h.dataset,h.rows,time(h.date),B('Download','export-history',h.id)]))))}
function exportFields(dataset){const fields=Object.keys(db()[dataset][0]||({orders:{id:0,customer:0,item:0,variant:0,address:0,status:0},audit:{id:0,date:0,actor:0,action:0,detail:0}}[dataset]||{id:0,name:0}));return fields.map((k,i)=>check(k,'field_'+k,i<8)).join('')}
function teamPage(){return page('The right access for every team.','Configure permissions and preview how each role experiences Ember.',B('＋ Add team member','team-new','',true))+tabs([['users','Team members'],['roles','Roles & scope']])+(tabIs('users','users')?panel('Workspace team',table(['NAME','EMAIL','ROLE','STATUS'],db().team.map(u=>[e(u.name),e(u.email),e(db().roles.find(r=>r.id===u.role)?.name||u.role),tag(u.status)]))):panel('Role permissions',table(['ROLE','PERMISSIONS','STORES','GIFT LIMIT','EXPORT',''],db().roles.map(r=>[e(r.name),r.permissions.length+' areas',r.stores.length?r.stores.map(id=>E.find('stores',id).name).join(', '):'All stores',r.giftLimit+' pts',r.export?'Allowed':'Blocked',r.id==='owner'?'Owner role':B('Edit','role-edit',r.id)])),B('Create role','role-new')))+notice('The role selector in the header is a demo impersonation tool. This local app cannot provide secure authentication or server-enforced access control.')}
function labPage(){return page('Try the idea before you spend.','Explore campaign economics and replay customer moments.')+`<div class="wide-grid">${panel('Campaign contribution forecast',`<form data-form="forecast"><div class="form-grid">${input('Eligible audience','audience',10000,'number','min="1" required')}${input('Conversion rate (%)','conversion',8,'number','min="0" max="100" step="0.1" required')}${input('Average basket (₹)','basket',650,'number','min="1" required')}${input('Gross margin (%)','margin',62,'number','min="0" max="100" required')}${input('Reward cost per order (₹)','reward',100,'number','min="0" required')}${input('Channel cost per message (₹)','messageCost',.25,'number','min="0" step="0.01" required')}</div><button class="primary">Calculate impact</button><p class="form-error"></p></form><div id="forecast-result" class="notice">Enter your assumptions to estimate contribution after reward and messaging costs.</div>`)}${panel('Simulation controls',`<div class="big-number">${date(db().now)}</div><p class="subtitle">Move time forward to process scheduled campaigns, delayed journey steps, renewals, exports, and point expiry.</p><div class="actions wrap" style="margin-top:20px">${B('Advance clock','clock','',true)}${B('Replay event','event-sim')}</div><h3 class="section-title">Latest changes</h3>${db().audit.slice(0,4).map(a=>`<div class="activity"><span>${e(a.action)}</span><small>${time(a.date)}</small></div>`).join('')}`)}</div>`}
const coverage=[['Loyalty models','loyalty','Points, visits, reward and currency conversion, tiers, expiry'],['Reward catalog','rewards','Create/edit, benefit types, costs, pause and eligibility'],['Coupons and promos','rewards','Shared/unique codes, expiration, limits, exports'],['Offer qualification','rewards','Item, category, tier, store, spend, caps, conditional and weighted gifts'],['Multiple redemptions','checkout','Stacking, priority, auto offers, basket lock, refunds'],['Customer profiles','customers','Consent, enrollment, ledger, referral and member history'],['Dynamic segmentation','segments','AND/OR, exclusion, dynamic/frozen audiences'],['Channel reachability','segments','Consent-based email/SMS/push counts'],['Smart segments','segments','11 transparent behavioral groups, campaign creation'],['Multichannel campaigns','campaigns','Local email/SMS/push delivery records'],['Lifecycle automation','journeys','Event triggers, actions, delays, follow-ups'],['Campaign operations','campaigns','A/B/holdout, approvals, scheduling, recurrence, audit, archive'],['Challenges / surveys / causes','engagement','Progress, point awards, referral caps and donations'],['Store configuration','stores','Groups, franchise, POS, hours and receipt text'],['Roles and permissions','team','Demo access scope, gift limits, exports'],['Reporting','analytics','Transaction, channel, item, offer, campaign, recency and monthly reports'],['Data exports','data','Fields, CSV, schedules, history and backup/restore'],['Fraud detection','fraud','Threshold rules, evidence, freeze and resolution'],['Integration workflows','integrations','Adapters, inbound idempotency, outbox, failures and retries'],['Paid memberships','memberships','Plans, enroll, recurring charges, usage caps, cancellation'],['Wallet passes','wallet','Apple/Google card preview, pass-data download'],['Loyalty payment','checkout','Identification, offers, stored-value and auto-reload simulation'],['Gamification','engagement','Weighted prizes, inventory, play and win limits'],['Merchandise','merchandise','SKUs, variants, stock, points checkout, fulfillment'],['Extra: contribution forecast','lab','Editable economics model with cost and margin sensitivity'],['Extra: audit and undo','settings','Central change history, recent-operation undo'],['Extra: scenario clock','lab','Repeatable event and time simulations'],['Extra: command search','overview','Keyboard shortcut and cross-module navigation']];
function coveragePage(){return page('A clear view of what Ember can do.','24 Punchh-based capability areas, plus tools for testing and decision-making.')+notice('All flows run locally. “Demo implemented” means interactive local behavior—not production parity, live provider connectivity, or verified superiority to Punchh.')+panel('Feature coverage',table(['CAPABILITY','IMPLEMENTED WORKFLOW','MODE',''],coverage.map(([n,r,d])=>[n,d,tag(['Wallet passes','Multichannel campaigns','Integration workflows','Paid memberships','Loyalty payment','Roles and permissions'].includes(n)?'Provider simulation':'Demo implemented'),link('Open →',r)])))+`<div class="store-strip">${panel('Production handoff',`<p>Live deployment requires a backend database, secure identity and authorization, message providers, payment/POS integrations, signed wallet passes, background workers, delivery monitoring, and operational testing.</p><p>Predictive AI and validated campaign lift are not implemented. Smart audiences use transparent rules; the growth lab uses explicit assumptions.</p>`)}</div>`}
function settingsPage(){return page('Your workspace, your way.','Preferences, reversible changes, and a complete local audit trail.',B('Undo last change','undo'))+tabs([['settings','Workspace settings'],['audit','Audit trail']])+(tabIs('settings','settings')?form('settings',`<div class="settings-grid">${panel('Workspace identity',input('Workspace name','workspace',db().settings.workspace,'text','required')+input('Reply-to email','reply',db().settings.reply,'email','required'))}${panel('Campaign controls',input('Messages per member / 7 days','frequencyCap',db().settings.frequencyCap,'number','min="1" max="20" required')+check('Require Owner approval','approvalRequired',db().settings.approvalRequired)+notice('Frequency caps and channel consent are evaluated when a campaign runs.'))}</div>`,'Save settings')+`<div class="store-strip">${panel('Local data management',`<div class="actions wrap">${B('Download backup','backup')}${B('Restore backup','restore')}${B('Reset expanded demo','reset-v3')}</div><p class="secondary">V1 files and legacy browser data remain preserved separately.</p>`)}</div>`:panel('Every change, accounted for',activity(),B('Export audit','export','audit')))}
Object.assign(pages,{overview:overviewPage,customers:customerPage,segments:segmentPage,loyalty:programPage,rewards:rewardsPage,campaigns:campaignPage,journeys:journeyPage,checkout:checkoutPage,memberships:membershipPage,wallet:walletPage,engagement:engagementPage,merchandise:merchandisePage,stores:storePage,analytics:analyticsPage,fraud:fraudPage,integrations:integrationsPage,data:dataPage,team:teamPage,lab:labPage,coverage:coveragePage,settings:settingsPage});
const A={
 close:()=>$('#modal').close(),tab:v=>{U.tab[state.route]=v;render()},'customer-detail':profile,'customer-new':()=>memberForm(),'customer-edit':memberForm,
 points:key=>{const c=E.find('customers',key);show('Adjust '+e(c.name)+"’s points",form('points',input('Adjustment (negative to deduct)','points',100,'number',`min="-${c.points}" max="${E.role().giftLimit}" required`)+input('Reason for adjustment','reason','','text','required')+notice('Your role can gift up to '+E.role().giftLimit+' points per adjustment. Every change is recorded.'),'Apply adjustment',key))},
 'segment-new':()=>segmentForm(),'segment-edit':segmentForm,'segment-freeze':key=>{E.freezeSegment(key);done('Audience mode updated')},
 'add-rule':()=>$('#segment-rules').insertAdjacentHTML('beforeend',ruleRow()),'add-exclusion':()=>$('#exclude-rules').insertAdjacentHTML('beforeend',ruleRow({},true)),
 'remove-rule':(key,b)=>b.closest('.rule-row').remove(),
 'preview-segment':()=>{const f=$('[data-form="segment"]');const s=readSegment(f);const all=E.segment('all');const match=(c,r)=>{const v=r.field==='days'?E.customerDays(c):c[r.field];return r.op==='gte'?+v>=+r.value:r.op==='lte'?+v<=+r.value:r.op==='neq'?String(v)!==r.value:r.op==='contains'?String(v).toLowerCase().includes(r.value.toLowerCase()):String(v)===r.value};let cs=all.filter(c=>(s.logic==='AND'?s.rules.every(r=>match(c,r)):s.rules.some(r=>match(c,r)))&&!s.exclude.some(r=>match(c,r)));$('#segment-preview').textContent=cs.length+' members · Email '+cs.filter(c=>c.consent.email&&c.status==='Active').length+' · SMS '+cs.filter(c=>c.consent.sms&&c.status==='Active').length+' · Push '+cs.filter(c=>c.consent.push&&c.status==='Active').length},
 'smart-detail':name=>show(e(name),table(['MEMBER','DAYS SINCE VISIT','SPEND',''],E.segment('smart:'+name).map(c=>[e(c.name),E.customerDays(c),money(c.spent),B('Profile','customer-detail',c.id)])),true),
 'offer-new':()=>offerForm(),'offer-edit':offerForm,'offer-toggle':key=>{E.toggle('offers',key,'active','offers');render();toast('Reward availability updated')},
 'offer-test':key=>{U.basket.offers=[key];U.quote=null;location.hash='checkout'},
 codes:()=>show('Generate coupon or promo codes',form('codes',`<div class="form-grid">${select('Code type','type',['Unique coupon','Shared promo'],'Unique coupon')}${input('Code prefix','prefix','MOD','text','required minlength="3" maxlength="20"')}${select('Reward','offer',oOptions(),'o2')}${input('Number of codes','count',10,'number','min="1" max="100" required')}${input('Total shared-code uses','limit',100,'number','min="1" required')}${input('Valid for days','days',30,'number','min="1" max="365" required')}</div>`,'Generate codes')),
 'dynamic-new':()=>show('Create dynamic reward rule',form('dynamic',input('Rule name','name','','text','required')+select('Distribution method','mode',['Conditional','Weighted surprise'],'Conditional')+`<div class="form-grid">${input('Lifetime spend threshold','threshold',800,'number','min="0" required')}${input('First reward weight (%)','weight',70,'number','min="0" max="100" required')}${select('Below threshold / first reward','low',oOptions(),'o1')}${select('At threshold / second reward','high',oOptions(),'o2')}</div>`,'Save rule')),
 'dynamic-issue':key=>show('Issue a dynamic gift',form('dynamic-issue',select('Member','customer',cOptions(),U.selected)+notice('The rule selects and issues an actual reward entitlement in the demo. Gifted rewards waive the points cost at checkout.'),'Issue reward',key)),
 'product-new':()=>show('Add catalog product',form('product',input('Product name','name','','text','required')+select('Category','category',['Drinks','Bakery','Food','Retail'],'Food')+`<div class="form-grid">${input('Selling price','price',250,'number','min="1" required')}${input('Unit cost','cost',100,'number','min="0" required')}</div>`,'Add product')),
 'campaign-new':v=>campaignFormX(v||'all'),'campaign-detail':campaignDetail,'campaign-filter':v=>{U.campaignStatus=v;render()},
 'campaign-action':v=>{const [key,action]=v.split('|');if(action==='Edit'){campaignFormX('all',key);return}E.campaignStatus(key,action);done('Campaign '+action.toLowerCase()+' completed')},
 'campaign-reach':()=>{const f=$('[data-form="campaign"]'),d=values(f);const c={...d,control:+d.control,ab:d.ab==='on'};let list=E.campaignReach(c);toast(list.length+' eligible members; '+Math.round(list.length*(+d.control/100))+' planned holdouts')},
 'journey-new':()=>journeyForm(),'journey-edit':key=>journeyForm(key),'journey-toggle':key=>{E.toggle('journeys',key,'active','campaigns');render();toast('Journey status updated')},
 'event-sim':()=>show('Replay a customer event',form('event-sim',select('Event','type',['Signup','Purchase','Redemption','Birthday','Profile update','Inactivity','Tier upgrade'],'Purchase')+select('Member','customer',cOptions(),U.selected)+notice('Event replay runs matching journeys. Use checkout for real demo transaction, earning, and challenge progress.'),'Run event')),
 'basket-add':()=>$('#basket-lines').insertAdjacentHTML('beforeend',`<div class="basket-line">${select('Product','product',options(db().products),'p1')}${input('Quantity','qty',1,'number','min="1" max="99" required')}${B('×','basket-remove')}</div>`),
 'basket-remove':(key,b)=>{b.closest('.basket-line').remove();U.quote=null},
 'checkout-commit':()=>{const current=readBasket($('[data-form="checkout-preview"]'));const t=E.commitCheckout(current,U.quote);U.basket={...current,reference:'DEMO-'+(db().seq+1)};U.quote=null;render();receipt(t.id);toast('Transaction completed. Balances and events updated.')},
 'receipt-list':()=>show('Recent demo receipts',table(['RECEIPT','MEMBER','NET','STATUS',''],db().transactions.slice(0,20).filter(t=>!E.role().stores.length||E.role().stores.includes(t.store)).map(t=>[e(t.reference),e(E.find('customers',t.customer).name),money(t.net),tag(t.status),B('View','receipt',t.id)])),true),receipt,
 refund:key=>{show('Refund this transaction?',`<p>The demo will reverse the purchase balance effects and record a refund event.</p>${notice('A completed transaction can only be refunded once. Downstream reward consumption may require manual review.')}<div class="actions">${B('Cancel','close')}${B('Confirm refund','refund-confirm',key,true)}</div>`)},
 'refund-confirm':key=>{E.refund(key);done('Transaction refunded')},
 'plan-new':()=>planForm(),'plan-edit':key=>planForm(key),'plan-toggle':key=>{E.toggle('plans',key,'active','memberships');render();toast('Plan availability updated')},
 'membership-enroll':()=>show('Enroll in a membership',form('membership-enroll',select('Member','customer',cOptions(),U.selected)+select('Plan','plan',options(db().plans.filter(p=>p.active)),'plan1')+notice('A simulated external payment is logged. The benefit becomes available immediately at checkout.'),'Enroll member')),
 'membership-cancel':key=>show('Cancel membership',form('membership-cancel',select('Cancellation reason','reason',['Not enough visits','Price','Benefits not relevant','Service issue','Other'],'Not enough visits')+notice('Cancellation takes effect immediately in this demo and prevents further renewal.'),'Confirm cancellation',key)),
 'member-open':key=>{U.selected=key||U.selected;$('#modal').close();location.hash='wallet';render()},
 'member-checkout':key=>{U.basket.customer=key;U.basket.payment='Stored value';U.quote=null;location.hash='checkout'},
 'wallet-topup':key=>show('Add demo stored value',form('wallet-topup',input('Amount (₹)','amount',500,'number','min="1" max="10000" required')+notice('No real charge is made. This balance can pay for simulated purchases.'),'Add value',key)),
 pass:v=>{const [key,platform]=v.split('|');E.pass(key,platform);render();toast(platform+' preview issued')},
 'pass-download':key=>{const c=E.find('customers',key);download('ember-member-pass.json',JSON.stringify({format:'Ember demo pass — not installable',name:c.name,tier:c.tier,points:c.points,...c.pass},null,2),'application/json');toast('Demo pass data downloaded')},
 auth:key=>{const c=E.find('customers',key);show('Preview secure sign-in',form('auth',select('Method','method',['OTP','Passkey'],'OTP')+input('Demo OTP','code','123456','text')+notice('Use demo code 123456. This simulates identity verification; it is not actual authentication.')+(c.passkey?tag('Demo passkey enrolled'):B('Enroll demo passkey','passkey',key)),'Verify in demo',key))},
 passkey:key=>{E.updateWallet(key,{passkey:true});A.auth(key);toast('Demo passkey enrolled')},
 'challenge-new':()=>show('Create a challenge',form('challenge',input('Challenge name','name','','text','required')+`<div class="form-grid">${input('Required visits','goal',3,'number','min="1" max="100" required')}${input('Points reward','reward',200,'number','min="1" max="10000" required')}</div>`+select('Qualifying category','category',['Any','Drinks','Bakery','Food','Retail'],'Any'),'Create challenge')),
 'challenge-progress':key=>{const ch=E.find('challenges',key);show(e(ch.name),notice('Complete a checkout to progress this challenge. Rewards issue automatically once the goal is reached.')+table(['MEMBER','PROGRESS','STATUS'],E.segment('all').slice(0,20).map(c=>[e(c.name),(ch.progress[c.id]||0)+' / '+ch.goal,tag(ch.claimed.includes(c.id)?'Rewarded':'In progress')])),true)},
 'survey-new':()=>show('Create a survey',form('survey-new',input('Survey name','name','','text','required')+input('Question (0–10 scale)','question','How likely are you to recommend MOD?','text','required')+input('Completion reward (points)','reward',50,'number','min="0" max="1000" required'),'Create survey')),
 survey:key=>{const s=E.find('surveys',key);show(e(s.name),form('survey',select('Member','customer',cOptions(),U.selected)+input(e(s.question),'rating',9,'number','min="0" max="10" required')+area('Tell us more','comment','','')+notice('Each member can earn this survey reward once.'),'Submit & earn '+s.reward+' points',key))},
 'cause-new':()=>show('Add a social cause',form('cause',input('Cause name','name','','text','required'),'Add cause')),
 donate:key=>show('Donate loyalty points',form('donate',select('Member','customer',cOptions(),U.selected)+input('Points to donate','points',100,'number','min="1" required')+notice('This records a points donation only; no real charitable payment is made.'),'Donate points',key)),
 'game-edit':key=>{const g=E.find('games',key);show('Configure reward game',form('game',input('Game name','name',g.name,'text','required')+`<div class="form-grid">${input('Daily plays per member','dailyPlays',g.dailyPlays,'number','min="1" max="10" required')}${input('Daily wins per member','dailyWins',g.dailyWins,'number','min="1" max="10" required')}${input('Remaining prize awards','stock',g.stock,'number','min="0" required')}</div><h3 class="section-title">Prize weights must total 100%</h3>${g.prizes.map((p,i)=>`<div class="form-grid">${input('Prize '+(i+1)+' name','prizeName'+i,p.name,'text','required')}${input('Points','prizePoints'+i,p.points,'number','min="0" required')}${input('Weight (%)','prizeWeight'+i,p.weight,'number','min="0" max="100" required')}</div>`).join('')}`,'Save game',key),true)},
 'game-play':key=>show('A little luck, a little loyalty',form('game-play',select('Member','customer',cOptions(),U.selected)+notice('Rewards use the configured weighted prize table and update the member’s points. Daily limits apply.'),'Reveal my reward',key)),
 'swag-new':()=>swagForm(),'swag-edit':key=>swagForm(key),
 'swag-redeem':key=>{const s=E.find('swag',key);show('Redeem '+e(s.name),form('swag-redeem',select('Member','customer',cOptions(),U.selected)+select('Variant','variant',Object.entries(s.variants).map(([v,n])=>[v,v+' · '+n+' in stock']),Object.keys(s.variants)[0])+select('Fulfillment','fulfillment',['Store pickup','Shipping'],'Store pickup')+area('Shipping address / pickup note','address','','')+notice('Cost: '+s.points+' points. Shipping is simulated; inventory is reserved immediately.'),'Place reward order',key))},
 fulfill:key=>{const o=E.find('orders',key);show('Fulfill order '+e(key),`<p><strong>${e(E.find('swag',o.item).name)} · ${e(o.variant)}</strong></p><p>${e(o.fulfillment)}: ${e(o.address||'Member’s home store')}</p><div class="actions">${B('Mark '+(o.fulfillment==='Shipping'?'shipped':'collected'),'fulfill-confirm',key,true)}</div>`)},
 'fulfill-confirm':key=>{E.atomic('engagement','Fulfilled merchandise order',()=>{const o=E.find('orders',key);o.status=o.fulfillment==='Shipping'?'Shipped':'Collected';return o});done('Fulfillment recorded')},
 'store-new':()=>storeForm(),'store-edit':key=>storeForm(key),'store-detail':key=>storeForm(key),
 'store-dashboard':key=>{U.store=key;location.hash='overview'},
 'fraud-rule-new':()=>fraudRuleForm(),'fraud-rule-edit':key=>fraudRuleForm(key),'fraud-rule-toggle':key=>{E.toggle('fraudRules',key,'active','fraud');render();toast('Fraud rule updated')},
 'fraud-sim':()=>{E.atomic('fraud','Created test fraud case',()=>{const f={id:E.id('case'),rule:db().fraudRules[0].id,customer:'c1',transaction:db().transactions[0].id,date:db().now,status:'Open',evidence:'75% discount — explicit test scenario',resolution:''};db().fraudCases.unshift(f);return f});render();toast('Test case added to the queue')},
 'fraud-detail':key=>{const f=E.find('fraudCases',key);show('Investigate '+e(f.id),`<h3>${e(E.find('customers',f.customer).name)}</h3>${notice(e(f.evidence))}${f.transaction?B('View transaction','receipt',f.transaction):''}<div class="metric-row">Rule<strong>${e(E.find('fraudRules',f.rule).name)}</strong></div>${form('fraud-resolve',select('Decision','action',['Dismiss as legitimate','Freeze member'],'Dismiss as legitimate')+area('Investigation note','reason',f.resolution),'Record decision',key)}${B('Open member profile','customer-detail',f.customer)}`)},
 'adapter-new':()=>adapterForm(),'adapter-edit':key=>adapterForm(key),'adapter-toggle':key=>{E.toggle('adapters',key,'active','integrations');render();toast('Adapter state updated')},'adapter-test':key=>{const r=E.testAdapter(key);render();toast('Test event: '+r.status)},
 'event-payload':key=>{const x=E.find('outbox',key);show('Event '+e(x.id),`<pre class="payload">${e(JSON.stringify(x,null,2))}</pre>`,true)},'event-retry':key=>{const r=E.retry(key);render();toast('Retry '+r.attempts+': '+r.status)},
 'export-toggle':key=>{E.toggle('exportJobs',key,'active','data');render();toast('Export schedule updated')},
 'export-history':key=>{const h=E.find('exportHistory',key);assertExport();download('ember-'+h.dataset+'.csv',csv(h.snapshot||db()[h.dataset],h.fields),'text/csv');toast('Report exported')},
 export:dataset=>{const fields={customers:['id','name','email','tier','points','visits','spent','store','status'],transactions:['id','date','reference','customer','store','gross','discount','net','points','payment','status'],offers:['id','name','kind','value','points','used','active'],coupons:['code','type','offer','used','limit','expires'],orders:['id','customer','item','variant','fulfillment','address','points','date','status'],audit:['date','actor','action','detail']}[dataset]||['id','name','status'];reportExport(dataset,fields)},
 backup:()=>{E.permission('settings');download('ember-workspace-backup.json',JSON.stringify(db(),null,2),'application/json');toast('Workspace backup downloaded')},
 restore:()=>show('Restore a local backup',`<p>Select a JSON backup generated by this expanded Ember prototype.</p><input id="restore-file" type="file" accept="application/json,.json" aria-label="Select Ember backup">${notice('Restoring replaces the current expanded demo data. Download a backup first if you want to keep your changes.')}<p id="restore-summary"></p><div id="restore-actions"></div>`),
 'restore-confirm':()=>{E.restore(U.pending);U.pending=null;done('Workspace restored')},
 'team-new':()=>show('Add a demo team member',form('team',input('Name','name','','text','required')+input('Email','email','','email','required')+select('Role','role',options(db().roles),'marketing')+notice('Adds a local team record. No invitation email is sent.'),'Add team member')),
 'role-new':()=>roleForm(),'role-edit':key=>roleForm(key),
 clock:()=>show('Advance the simulation clock',form('clock',input('Days to advance','days',7,'number','min="0" max="365" required')+notice('Processes due campaigns, journeys, membership renewals, exports, and points expiry. Use Undo to reverse the entire clock step.'),'Advance and process')),
 undo:()=>{const label=E.undo();render();toast('Undid: '+label)},
 'reset-v3':()=>show('Reset expanded demo?',`<p>This replaces the expanded workspace with its original sample data. Your V1 files remain intact.</p><div class="actions">${B('Download backup first','backup')}${B('Reset expanded demo','reset-confirm','',true)}</div>`),
 'reset-confirm':()=>{E.reset();U.store='all';U.selected='c1';U.quote=null;done('Demo restored to starting state')},
 notifications:()=>show('Workspace activity',db().notifications.length?table(['EVENT','MEMBER','WHEN'],db().notifications.slice(0,12).map(n=>[e(n.type),n.customer?e(E.find('customers',n.customer).name):'—',time(n.date)])):notice('Run a checkout, campaign, or journey to populate the event stream.')),
 command:()=>show('Go anywhere in Ember',`<input id="command-search" class="search" placeholder="Search features, customers, campaigns…" aria-label="Search workspace" autofocus><div id="command-results">${commandResults('')}</div>`,true)
};
function values(f){return Object.fromEntries(new FormData(f))}
function numberFields(d,keys){for(const k of keys)d[k]=Number(d[k]);return d}
function readSegment(f){const d=values(f),read=selector=>[...f.querySelectorAll(selector+' .rule-row')].map(row=>({field:row.querySelector('[name="field"]').value,op:row.querySelector('[name="op"]').value,value:row.querySelector('[name="value"]').value}));return {name:d.name,logic:d.logic,rules:read('#segment-rules'),exclude:read('#exclude-rules'),tags:d.tags.split(',').map(x=>x.trim()).filter(Boolean)}}
function readBasket(f){const d=values(f);return {customer:d.customer,store:d.store,channel:d.channel,payment:d.payment,code:d.code,reference:d.reference,campaign:d.campaign,offers:db().offers.filter(o=>d['offer_'+o.id]==='on').map(o=>o.id),lines:[...f.querySelectorAll('.basket-line')].map(row=>({product:row.querySelector('[name="product"]').value,qty:Number(row.querySelector('[name="qty"]').value)}))}}
function receipt(key){const t=E.find('transactions',key);show('Receipt '+e(t.reference),`<div class="section-heading"><h3>${e(E.find('customers',t.customer).name)}</h3>${tag(t.status)}</div><p class="subtitle">${e(E.find('stores',t.store).name)} · ${time(t.date)}</p>${table(['ITEM','QUANTITY'],t.lines.map(l=>[e(E.find('products',l.product).name),l.qty]))}<div class="metric-row">Subtotal<strong>${money(t.gross)}</strong></div><div class="metric-row">Discount<strong>−${money(t.discount)}</strong></div><div class="metric-row">Paid<strong>${money(t.net)}</strong></div><div class="metric-row">Points earned<strong>${t.points}</strong></div><p class="secondary">${e(t.payment)} · ${e(t.channel)}</p><div class="actions">${B('Member profile','customer-detail',t.customer)}${t.status==='Completed'?B('Refund in demo','refund',key):''}</div>`,true)}
function journeyForm(key){const j=key?E.find('journeys',key):{name:'',trigger:'Purchase',action:'Points',value:100,offer:'o1',delay:0,followDelay:3,follow:'Email',active:true,enrolled:0};show('Configure customer journey',form('journey',input('Journey name','name',j.name,'text','required')+`<div class="form-grid">${select('Trigger','trigger',['Signup','Purchase','Redemption','Birthday','Profile update','Inactivity','Tier upgrade'],j.trigger)}${select('Action','action',['Points','Offer','Email','SMS','Push'],j.action)}${input('Points to award','value',j.value,'number','min="0" max="10000" required')}${select('Reward to issue','offer',oOptions(),j.offer)}${input('Delay before action (days)','delay',j.delay,'number','min="0" max="365" required')}${input('Follow-up after action (days)','followDelay',j.followDelay,'number','min="1" max="365" required')}${select('Follow-up channel','follow',['Email','SMS','Push'],j.follow)}</div>`+check('Activate journey','active',j.active),'Save journey',key||''),true)}
function planForm(key){const p=key?E.find('plans',key):{name:'',price:399,days:30,benefit:15,category:'Drinks',maxUses:30,dailyUses:1,active:true};show('Configure membership plan',form('plan',input('Plan name','name',p.name,'text','required')+`<div class="form-grid">${input('Price (₹)','price',p.price,'number','min="1" required')}${input('Renew every (days)','days',p.days,'number','min="1" max="365" required')}${input('Discount (%)','benefit',p.benefit,'number','min="1" max="100" required')}${select('Eligible category','category',['Any','Drinks','Bakery','Food','Retail'],p.category)}${input('Maximum uses / period','maxUses',p.maxUses,'number','min="1" max="1000" required')}${input('Maximum uses / day','dailyUses',p.dailyUses,'number','min="1" max="100" required')}</div>`+check('Active','active',p.active),'Save plan',key||''))}
function swagForm(key){const s=key?E.find('swag',key):{name:'',sku:'MOD-',points:1500,variants:{Standard:20},active:true};show('Configure merchandise',form('swag',input('Product name','name',s.name,'text','required')+input('SKU','sku',s.sku,'text','required')+input('Points price','points',s.points,'number','min="1" required')+area('Variants and stock (one per line: Red: 20)','variants',Object.entries(s.variants).map(([v,n])=>v+': '+n).join('\n'))+check('Available for redemption','active',s.active),'Save merchandise',key||''))}
function storeForm(key){const s=key?E.find('stores',key):{name:'',city:'',group:'Company stores',franchise:'Company owned',manager:'',hours:'08:00–23:00',timezone:'Asia/Kolkata',pos:'Connected',receipt:'Thank you for visiting MOD.',enabled:true};show(key?'Configure '+e(s.name):'Add a store',form('store',`<div class="form-grid">${input('Store name','name',s.name,'text','required')}${input('City','city',s.city,'text','required')}${input('Location group','group',s.group,'text','required')}${input('Franchise','franchise',s.franchise,'text','required')}${input('Manager','manager',s.manager,'text','required')}${input('Opening hours','hours',s.hours,'text','required')}${select('POS status','pos',['Connected','Maintenance','Disconnected'],s.pos)}${input('Timezone','timezone',s.timezone,'text','required')}</div>`+area('Receipt message','receipt',s.receipt)+check('Store enabled','enabled',s.enabled),'Save store',key||''),true)}
function fraudRuleForm(key){const r=key?E.find('fraudRules',key):{name:'',type:'Discount percent',threshold:60,active:true};show('Configure detection rule',form('fraud-rule',input('Rule name','name',r.name,'text','required')+select('Flag when threshold is reached','type',['Discount percent','Daily transactions','Manual points'],r.type)+input('Threshold','threshold',r.threshold,'number','min="1" required')+check('Rule active','active',r.active),'Save rule',key||''))}
function adapterForm(key){const a=key?E.find('adapters',key):{name:'',kind:'Custom webhook',url:'https://partner.example.com/events',active:true,failure:false,events:['Purchase']};show('Configure local adapter',form('adapter',input('Connection name','name',a.name,'text','required')+select('Adapter','kind',['Custom webhook','Braze','mParticle','Salesforce Marketing Cloud','SMS partner','POS'],a.kind)+input('Endpoint (display only)','url',a.url,'url','required')+`<h3 class="section-title">Subscribed events</h3><div class="field-checks">${['Purchase','Refund','Signup','Customer updated','Reward issued','Campaign delivered','Membership started','Membership renewed','Pass issued'].map(t=>check(t,'event_'+t,a.events.includes(t))).join('')}</div>`+check('Connection active','active',a.active)+check('Simulate upstream failure (503)','failure',a.failure)+notice('No credentials are requested and no events leave this browser.'),'Save adapter',key||''),true)}
function roleForm(key){const r=key?E.find('roles',key):{name:'',permissions:['customers'],giftLimit:200,stores:[],export:false};show('Configure demo role',form('role',input('Role name','name',r.name,'text','required')+`<h3 class="section-title">Permission areas</h3><div class="field-checks">${EmberEngine.SCOPES.map(s=>check(s,'permission_'+s,r.permissions.includes(s))).join('')}</div><h3 class="section-title">Store access (none selected means all)</h3><div class="field-checks">${db().stores.map(s=>check(e(s.name),'store_'+s.id,r.stores.includes(s.id))).join('')}</div>`+input('Maximum manual points gift','giftLimit',r.giftLimit,'number','min="0" max="10000" required')+check('Allow exports','export',r.export),'Save role',key||''),true)}
function commandResults(query){const q=query.toLowerCase();const links=groups.flatMap(g=>g[1]).filter(([id,label])=>accessible(id)&&label.toLowerCase().includes(q)).map(([id,label])=>`<a class="command-item" href="#${id}" data-do="close"><strong>${label}</strong><span>Workspace →</span></a>`);const members=q?E.segment('all').filter(c=>(c.name+' '+c.email).toLowerCase().includes(q)).slice(0,5).map(c=>`<button class="command-item" data-do="customer-detail" data-id="${c.id}"><strong>${e(c.name)}</strong><span>Member →</span></button>`):[];return [...links,...members].join('')||empty('No matches')}
document.addEventListener('click',event=>{const b=event.target.closest('[data-do]');if(!b)return;const action=A[b.dataset.do];if(!action)return;try{action(b.dataset.id,b)}catch(err){const error=$('#modal[open] .form-error');if(error)error.textContent=err.message;toast(err.message)}});
document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();A.command()}});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='x-store'){U.store=el.value;render()}else if(el.id==='x-period'){U.period=+el.value;render()}else if(el.id==='x-tier'){U.tier=el.value;render()}else if(el.id==='x-role'){E.setRole(el.value);U.store='all';if(E.role().stores.length){U.basket.store=E.role().stores[0];const member=E.segment('all')[0];if(member){U.selected=member.id;U.basket.customer=member.id}}U.quote=null;render();toast('Previewing '+E.role().name+' permissions')}else if(el.id==='x-member'){U.selected=el.value;render()}else if(el.id==='export-dataset'){U.dataset=el.value;$('#export-fields').innerHTML=exportFields(el.value)}else if(el.id==='restore-file'){const file=el.files[0];if(!file)return;if(file.size>5000000){toast('Backup must be smaller than 5 MB');return}file.text().then(text=>{const data=JSON.parse(text);if(data.version!==3)throw Error('Not an expanded Ember backup');U.pending=data;$('#restore-summary').textContent=data.customers.length+' customers · '+data.transactions.length+' transactions';$('#restore-actions').innerHTML=B('Replace workspace with backup','restore-confirm','',true)}).catch(err=>toast('Invalid backup: '+err.message))}});
document.addEventListener('input',event=>{if(event.target.id==='x-search'){const start=event.target.selectionStart;U.search=event.target.value;render();$('#x-search').focus();$('#x-search').setSelectionRange(start,start)}if(event.target.id==='command-search')$('#command-results').innerHTML=commandResults(event.target.value)});
document.addEventListener('submit',event=>{const f=event.target;if(!f.matches('[data-form]'))return;event.preventDefault();const d=values(f),key=f.dataset.id,type=f.dataset.form;try{let message='Changes saved';switch(type){
 case 'customer-new':E.addCustomer({...d,consent:Object.fromEntries(['email','sms','push'].map(k=>[k,d['consent_'+k]==='on']))});message='Member enrolled; signup journeys processed';break;
 case 'customer-edit':E.editCustomer(key,{name:d.name,email:d.email,store:d.store,birthday:d.birthday,tags:d.tags.split(',').map(x=>x.trim()).filter(Boolean),consent:Object.fromEntries(['email','sms','push'].map(k=>[k,d['consent_'+k]==='on']))});message='Profile and consent updated';break;
 case 'points':E.adjust(key,+d.points,d.reason);message='Points adjusted and audited';break;
 case 'segment':E.saveSegment({...readSegment(f),id:key||undefined});message='Audience saved';break;
 case 'program':numberFields(d,['earn','visitGoal','threshold','currencyRate','expiryDays','dailyCap','maxRedemptions','tierSilver','tierGold','silverMultiplier','goldMultiplier']);d.stacking=d.stacking==='on';d.lock=d.lock==='on';E.configureProgram(d);break;
 case 'offer':numberFields(d,['value','points','minSpend','max','priority']);if(d.kind==='Percentage'&&d.value>100)throw Error('Percentage cannot exceed 100');if(!Number.isInteger(d.points))throw Error('Points must be whole numbers');d.expiry=Date.parse(d.expiry+'T23:59:59Z');if(d.expiry<db().now)throw Error('Choose a future expiry');d.stores=d.store==='all'?[]:[d.store];d.exclude=d.exclude==='None'?null:d.exclude;['auto','stackable','active'].forEach(k=>d[k]=d[k]==='on');E.upsert('offers',{...d,id:key||undefined,used:key?E.find('offers',key).used:0},'offers');message='Offer rules saved';break;
 case 'codes':E.generateCodes(d);message='Codes generated';break;
 case 'dynamic':numberFields(d,['threshold','weight']);E.upsert('dynamicRules',d,'offers');break;
 case 'dynamic-issue':{const o=E.issueDynamic(key,d.customer);message='Issued: '+o.name;break}
 case 'product':numberFields(d,['price','cost']);E.upsert('products',d,'offers');break;
 case 'campaign':if(key)d.id=key;d.scheduled=d.scheduled?Date.parse(d.scheduled):null;if(d.scheduled&&d.scheduled<db().now)throw Error('Choose a time after the simulation clock');numberFields(d,['repeat','control','budget']);d.tags=d.tags.split(',').map(x=>x.trim()).filter(Boolean);d.ab=d.ab==='on';d.submit=d.submit==='on';E.saveCampaign(d);U.campaignStatus='All';message=d.submit?'Campaign submitted for Owner approval':'Draft saved';break;
 case 'journey':numberFields(d,['value','delay','followDelay']);E.upsert('journeys',{...d,id:key||undefined,active:d.active==='on',enrolled:key?E.find('journeys',key).enrolled:0},'campaigns');break;
 case 'event-sim':E.simulateEvent(d.type,d.customer);message='Matching journeys processed';break;
 case 'checkout-preview':U.basket=readBasket(f);U.quote=E.quote(U.basket);render();toast('Basket evaluated and locked');return;
 case 'plan':numberFields(d,['price','days','benefit','maxUses','dailyUses']);E.upsert('plans',{...d,id:key||undefined,active:d.active==='on'},'memberships');break;
 case 'membership-enroll':E.enrollMembership(d.customer,d.plan);message='Membership active; simulated payment recorded';break;
 case 'membership-cancel':E.cancelMembership(key,d.reason);message='Membership cancelled';break;
 case 'wallet-topup':E.wallet(key,+d.amount);message='Demo balance updated';break;
 case 'wallet-prefs':E.updateWallet(key,{autoReload:d.autoReload==='on',reloadThreshold:+d.reloadThreshold,reloadAmount:+d.reloadAmount});break;
 case 'auth':E.auth(key,d.method,d.code);message='Sign-in verified in demo';break;
 case 'challenge':numberFields(d,['goal','reward']);E.upsert('challenges',{...d,active:true,progress:{},claimed:[]},'engagement');break;
 case 'survey-new':d.reward=+d.reward;E.upsert('surveys',{...d,active:true,responses:[]},'engagement');break;
 case 'survey':E.survey(key,d.customer,+d.rating,d.comment);message='Feedback saved; points awarded';break;
 case 'cause':E.upsert('causes',{...d,points:0,donations:0},'engagement');break;
 case 'donate':E.donate(key,d.customer,+d.points);message='Points donation recorded';break;
 case 'game':{const prizes=[0,1,2].map(i=>({name:d['prizeName'+i],points:+d['prizePoints'+i],weight:+d['prizeWeight'+i]}));if(prizes.reduce((s,p)=>s+p.weight,0)!==100)throw Error('Prize weights must total 100%');E.upsert('games',{id:key,name:d.name,dailyPlays:+d.dailyPlays,dailyWins:+d.dailyWins,stock:+d.stock,prizes},'engagement');break}
 case 'game-play':{const result=E.play(key,d.customer);render();show('Your daily reward',`<div class="game-result"><span>✦</span><h1>${e(result.prize)}</h1><p>${result.points?'The points are already in your account.':'A new chance awaits tomorrow.'}</p>${B('View member','customer-detail',d.customer,true)}</div>`);return}
 case 'swag':{const variants={};d.variants.split('\n').filter(Boolean).forEach(line=>{const [name,n]=line.split(':');if(!name?.trim()||!Number.isInteger(+n)||+n<0)throw Error('Use Variant: whole stock number on each line');variants[name.trim()]=+n});if(!Object.keys(variants).length)throw Error('Add a variant');E.upsert('swag',{id:key||undefined,name:d.name,sku:d.sku,points:+d.points,variants,active:d.active==='on'},'engagement');break}
 case 'swag-redeem':E.orderSwag(key,d.customer,d.variant,d.fulfillment,d.address);message='Order placed; points deducted and stock reserved';break;
 case 'store':E.upsert('stores',{...d,id:key||undefined,enabled:d.enabled==='on'},'settings');break;
 case 'fraud-rule':E.upsert('fraudRules',{...d,id:key||undefined,threshold:+d.threshold,active:d.active==='on'},'fraud');break;
 case 'fraud-resolve':E.fraudResolve(key,d.action,d.reason);message='Investigation decision recorded';break;
 case 'adapter':E.upsert('adapters',{id:key||undefined,name:d.name,kind:d.kind,url:d.url,active:d.active==='on',failure:d.failure==='on',events:Object.keys(d).filter(k=>k.startsWith('event_')).map(k=>k.slice(6))},'integrations');break;
 case 'inbound':E.inbound(d.customer,+d.points,d.reference);message='Partner award processed once';break;
 case 'export':{const fields=Object.keys(d).filter(k=>k.startsWith('field_')).map(k=>k.slice(6));if(!fields.length)throw Error('Select at least one field');reportExport(d.dataset,fields);if(d.recurring==='on')E.upsert('exportJobs',{name:d.name,dataset:d.dataset,fields,cadence:+d.cadence,next:db().now+(+d.cadence)*D,active:true},'data');else E.atomic('data','Exported data',()=>{db().exportHistory.unshift({id:E.id('export'),job:'On-demand export',dataset:d.dataset,date:db().now,fields,rows:db()[d.dataset].length,snapshot:JSON.parse(JSON.stringify(db()[d.dataset])),status:'Ready'});return d.dataset});render();return}
 case 'team':E.upsert('team',{...d,status:'Active'},'team');message='Local team member added';break;
 case 'role':E.upsert('roles',{id:key||undefined,name:d.name,giftLimit:+d.giftLimit,export:d.export==='on',permissions:EmberEngine.SCOPES.filter(s=>d['permission_'+s]==='on'),stores:db().stores.filter(s=>d['store_'+s.id]==='on').map(s=>s.id)},'team');break;
 case 'clock':message=E.advance(+d.days);U.quote=null;break;
 case 'forecast':{numberFields(d,['audience','conversion','basket','margin','reward','messageCost']);const purchases=d.audience*d.conversion/100,revenue=purchases*d.basket,expense=purchases*d.reward+d.audience*d.messageCost,contribution=revenue*d.margin/100-expense;$('#forecast-result').innerHTML=`<div class="forecast-grid"><div>Expected orders<strong>${number(purchases)}</strong></div><div>Expected revenue<strong>${money(revenue)}</strong></div><div>Reward + channel cost<strong>${money(expense)}</strong></div><div>Net contribution<strong class="${contribution>=0?'positive':'negative'}">${money(contribution)}</strong></div></div><p>Scenario based on your assumptions; this is not a prediction of incremental lift.</p>`;return}
 case 'settings':E.configureSettings({workspace:d.workspace,reply:d.reply,frequencyCap:+d.frequencyCap,approvalRequired:d.approvalRequired==='on'});break;
 default:return}
 done(message);
 }catch(err){const error=f.querySelector('.form-error');if(error)error.textContent=err.message;toast(err.message)}});
window.EmberUI={E,U,B,e,input,select,check,area,form,panel,notice,table,metrics,page,show,done,tag,options,date,money,number,groups,scopes,A,profile,download,csv,coverage};
// Keep legacy shell actions connected to the expanded data model.
window.actions.settings=()=>location.hash='settings';window.actions.notifications=A.notifications;
render();
if(document.modelContext?.registerTool){const life=new AbortController();const tools=[{name:'ember_open_section',description:'Open an Ember demo section without changing records.',inputSchema:{type:'object',properties:{section:{type:'string',enum:routes.map(r=>r[0])}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({section})=>{if(!routes.some(r=>r[0]===section)||!accessible(section))throw Error('Unknown or inaccessible section');location.hash=section;state.route=section;render();return{section}}},{name:'ember_read_demo_summary',description:'Read local demo counts and current simulation date.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({customers:E.segment('all').length,transactions:E.totals('all',365).visits,clock:new Date(db().now).toISOString(),role:E.role().name})}];for(const t of tools){try{Promise.resolve(document.modelContext.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>life.abort(),{once:true})}
})();
